# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OtomatisasiD3TLH
                                 A QGIS plugin
 Plugin yang membantu pengolahan D3TLH secara otomatis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-15
        copyright            : (C) 2025 by Yayasan Lokahita
        email                : fadillahazhardk@yayasanlokahita.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yayasan Lokahita'
__date__ = '2025-08-15'
__copyright__ = '(C) 2025 by Yayasan Lokahita'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterEnum,   # ini perlu ditambah
                       QgsSpatialIndex,
                       QgsVectorLayer,
                       edit)
import processing
import os


class JLHPendukungKehati(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    PENUTUP_LAHAN = 'PENUTUP_LAHAN'
    EKOREGION = 'EKOREGION'
    GRID = 'GRID'
    BENTUK_OUTPUT = 'BENTUK_OUTPUT'
    SKOR_JLH = 'SKOR_JLH'
    PULAU = 'PULAU'

    bentuk_output_list = ['Grid', 'Poligon']
    skor_jlh_list = ['Kabupaten/Kota', 'Nasional']  # menentukan sumber file skor
    pulau_list = ['Jawa', 'Sumatera', 'Kalimantan', 'Sulawesi', 'BaliNusra', 'Maluku', 'Papua']

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # Pulau (boleh multi, default semua)
        self.addParameter(
            QgsProcessingParameterEnum(
                self.PULAU,
                self.tr('Pulau (untuk skor PL)'),
                options=self.pulau_list,
                allowMultiple=True,
                defaultValue=list(range(len(self.pulau_list)))
            )
        )

        # Bentuk output
        self.addParameter(
            QgsProcessingParameterEnum(
                self.BENTUK_OUTPUT,
                self.tr('Bentuk Output'),
                options=self.bentuk_output_list,
                defaultValue=1  # Grid
            )
        )

        # Sumber skor IJLH
        self.addParameter(
            QgsProcessingParameterEnum(
                self.SKOR_JLH,
                self.tr('Skor IJLH yang Digunakan'),
                options=self.skor_jlh_list,
                defaultValue=1  # Nasional
            )
        )

        # We add the input vector features source. It can have any kind of
        # geometry.

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.PENUTUP_LAHAN,
                self.tr('Penutup Lahan'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.EKOREGION,
                self.tr('Ekoregion'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )
        
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.GRID,
                self.tr('Grid'),
                [QgsProcessing.TypeVectorAnyGeometry],
                optional=True
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('JLH Keanekaragaman Hayati')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        pl = parameters["PENUTUP_LAHAN"]
        ekoregion = parameters["EKOREGION"]
        grid = parameters["GRID"]

        bentuk_output = self.bentuk_output_list[self.parameterAsEnum(parameters, self.BENTUK_OUTPUT, context)]
        skor_jlh = self.skor_jlh_list[self.parameterAsEnum(parameters, self.SKOR_JLH, context)]
        pulau_idx_list = self.parameterAsEnums(parameters, self.PULAU, context)
        selected_islands = [self.pulau_list[i] for i in pulau_idx_list] if pulau_idx_list else self.pulau_list

        # Validasi pilihan pulau untuk mode Kabupaten/Kota
        if skor_jlh == 'Kabupaten/Kota':
            # pulau_idx_list adalah list index yang dipilih pada parameter Pulau
            if pulau_idx_list is None or len(pulau_idx_list) != 1:
                raise Exception(self.tr(
                    'Untuk mode "Kabupaten/Kota", Anda harus memilih tepat 1 pulau pada parameter "Pulau".'
                ))

        ## LIHAT DIMANA DATA LOAD DATA INTERNAL NYA MASUK!! UNTUK KEHATI (IBA, KBA, Karst, Mangrove dan Gambut)
        def load_internal_layer(relative_path, layer_name="internal_layer"):
            plugin_dir = os.path.dirname(os.path.dirname(__file__))  # naik satu level ke root plugin
            data_path = os.path.join(plugin_dir, "..\data\jlh_phk\KK", relative_path)
            if not os.path.exists(data_path):
                raise Exception(f"File tidak ditemukan: {data_path}")
            vlayer = QgsVectorLayer(data_path, layer_name, "ogr")
            if not vlayer.isValid():
                raise Exception(f"Gagal memuat layer internal: {data_path}")
            return vlayer

        
        def joinSkorMatra(source, matra, pulau=None): 
            # Load CSV file containing score values for PL, KBA, and KVA     
            if skor_jlh == 'Kabupaten/Kota' and matra == 'pl':
                match pulau.lower():
                    case 'jawa':
                        skor_file_name = "skor_pl_phk_jawa.csv"
                    case 'sumatera':
                        skor_file_name = "skor_pl_phk_sumatera.csv"
                    case 'kalimantan':
                        skor_file_name = "skor_pl_phk_kalimantan.csv"
                    case 'sulawesi':
                        skor_file_name = "skor_pl_phk_sulawesi.csv"
                    case 'balinusra':
                        skor_file_name = "skor_pl_phk_balinusra.csv"
                    case 'maluku':
                        skor_file_name = "skor_pl_phk_maluku.csv"
                    case 'papua':
                        skor_file_name = "skor_pl_phk_papua.csv"
                csv_path_skor = f"{os.path.dirname(__file__)}/../../data/jlh_phk/kabupaten_kota/{skor_file_name}"  # Update with the actual path to your CSV file
            else:
                match matra.lower():
                    case 'kba':
                        skor_file_name = "skor_kba_phk.csv"
                    case 'kva':
                        skor_file_name = "skor_kva_phk.csv"
                    case 'pl':
                        skor_file_name = "skor_pl_phk.csv"     
                csv_path_skor = f"{os.path.dirname(__file__)}/../../data/jlh_phk/{skor_file_name}"  # Update with the actual path to your CSV file
            
            uri_skor = f"file:///{csv_path_skor}?encoding=UTF-8&delimiter=;"

            skor = QgsVectorLayer(uri_skor, "csv_internal", "delimitedtext")

            # Join Skor to the intersection layer
            match matra.lower():
                case 'kba':
                    params = {
                        'INPUT': source,
                        'FIELD': 'KBA_250',
                        'INPUT_2': skor,
                        'FIELD_2': 'EKOREGION',
                        'FIELDS_TO_COPY': ['S_EK'],
                        'METHOD': 0,
                        'DISCARD_NONMATCHING': False,
                        'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                    }
                case 'kva':
                    params = {
                        'INPUT': source,
                        'FIELD': 'KVA_250',
                        'INPUT_2': skor,
                        'FIELD_2': 'VEGETASI',
                        'FIELDS_TO_COPY': ['S_VE'],
                        'METHOD': 0,
                        'DISCARD_NONMATCHING': False,
                        'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                    }
                case 'pl':
                    params = {
                        'INPUT': source,
                        'FIELD': 'LC',
                        'INPUT_2': skor,
                        'FIELD_2': 'LC',
                        'FIELDS_TO_COPY': ['S_LC'],
                        'METHOD': 0,
                        'DISCARD_NONMATCHING': False,
                        'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                    }

            return processing.run("qgis:joinattributestable", params)["OUTPUT"]

        # Intersection of the two layers (Penutup Lahan and Ekoregion (KBA, KVA))
        intersection_params = {
            'INPUT': pl, 
            'OVERLAY': ekoregion,
            'INPUT_FIELDS': ['LC'],
            'OVERLAY_FIELDS': ['KBA_250', 'KVA_250'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }

        source_intersect = processing.run("qgis:intersection", intersection_params)["OUTPUT"]
        
        feedback.pushInfo(f"✅ Intersection antara Penutup Lahan dan Ekoregion berhasil, total fitur: {source_intersect.featureCount()}")

        # Join Skor Matra To Intersection Layer
        source_kba = joinSkorMatra(source_intersect, 'kba', selected_islands[0] if skor_jlh == 'Kabupaten/Kota' else None)
        source_kva = joinSkorMatra(source_kba, 'kva', selected_islands[0] if skor_jlh == 'Kabupaten/Kota' else None)
        source_pl = joinSkorMatra(source_kva, 'pl', selected_islands[0] if skor_jlh == 'Kabupaten/Kota' else None)
        
        # Calcule Jasling  [BOBOT PERLU DIRUBAH UNTUK JLH LAIN]
        bobot_ek = 0.24  # Bobot Ekoregion
        bobot_ve = 0.16  # Bobot Vegetasi
        bobot_lc = 0.6  # Bobot Penutup Lahan
        
        calculator_params =  {
                'INPUT': source_pl,
                'FIELD_NAME': 'JLH_Kehati',
                'FIELD_TYPE': 0,             # 0 = Float
                'FIELD_LENGTH': 20,
                'FIELD_PRECISION': 3,
                'NEW_FIELD': True,
                'FORMULA': f'"S_EK" * {bobot_ek} + "S_VE" * {bobot_ve} + "S_LC" * {bobot_lc}',  # multiply three fields
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        source_calc_jasling = processing.run("qgis:fieldcalculator", calculator_params)["OUTPUT"]

        feedback.pushInfo("✅ Perhitungan JLH_Kehati berhasil")

        # Load semua layer internal yang ada di KK
        iba_layer = load_internal_layer("IBA.shp", "IBA")
        kba_layer = load_internal_layer("KBA.shp", "KBA")
        karst_layer = load_internal_layer("Karst.shp", "Karst")
        mangrove_layer = load_internal_layer("Mangrove.shp", "Mangrove")
        gambut_layer = load_internal_layer("Gambut.shp", "Gambut")

        # Gabungkan semua layer internal KK menjadi satu
        merge_params = {
            'INPUT': iba_layer,
            'OVERLAYS': [kba_layer, karst_layer, mangrove_layer, gambut_layer],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }

        merged_layer = processing.run("qgis:multiunion", merge_params)["OUTPUT"]

        fixed_merged_layer = processing.run(
            "native:fixgeometries",
            {
                'INPUT': merged_layer,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        )["OUTPUT"]

        # Menambahkan kolom KK
        calculator_params = {
            'INPUT': fixed_merged_layer,
            'FIELD_NAME': 'KK',
            'FIELD_TYPE': 1,  # Integer
            'FIELD_LENGTH': 1,
            'FIELD_PRECISION': 0,
            'NEW_FIELD': True,
            'FORMULA': '1',
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        merged_layer_kk = processing.run("qgis:fieldcalculator", calculator_params)["OUTPUT"]

        clip_merged_layer_kk = processing.run(
            "qgis:clip",
            {
                'INPUT': merged_layer_kk,
                'OVERLAY': source_calc_jasling,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        )["OUTPUT"]

        # Cek jumlah fitur
        feedback.pushInfo(f"✅ Semua layer internal berhasil digabung, total fitur: {merged_layer.featureCount()}")
        
        # Proses untuk output bentuk POLIGON atau GRID
        # ============================================================
        if bentuk_output == 'Poligon':
            # 1. Intersection dengan merged_layer (KK + kriteria khusus)
            inter_params = {
                'INPUT': source_calc_jasling,
                'OVERLAY': clip_merged_layer_kk,
                'INPUT_FIELDS': [],
                'OVERLAY_FIELDS': ['KK'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            intersected = processing.run("qgis:intersection", inter_params, context=context, feedback=feedback)["OUTPUT"]

            feedback.pushInfo(f"✅ Intersection dengan layer KK dan kriteria khusus berhasil, total fitur: {intersected.featureCount()}")

            # 1a. Difference dengan merged_layer (KK + kriteria khusus) untuk mendapatkan fitur diluar area KK
            diff_params = {
                'INPUT': source_calc_jasling,
                'OVERLAY': clip_merged_layer_kk,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            diffed = processing.run("qgis:difference", diff_params, context=context, feedback=feedback)["OUTPUT"]

            # 1b. Gabungkan hasil intersect dan difference
            merge_final_params = {
                'LAYERS': [intersected, diffed],
                'CRS': intersected.crs(),  # gunakan CRS salah satu layer (sudah dalam kondisi EPSG : 4326)
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            merged_jlh_kk = processing.run("qgis:mergevectorlayers", merge_final_params, context=context, feedback=feedback)["OUTPUT"]

            # 2. Override (Membuat skor menjadi auto 5) JLH_Kehati sesuai rules (KK, Savana, Tubuh Air)
            override_formula = '''
            CASE
                WHEN "KK" = 1 THEN 5
                WHEN "LC" = 'Savana/Padang Rumput' AND "KODE_PROV" IN (51,52,53,91,92,94,95,96) THEN 5
                WHEN "LC" IN ('Tubuh Air','Badan Air') THEN 5
                ELSE "JLH_Kehati"
            END
            '''
            override_params = {
                'INPUT': merged_jlh_kk,
                'FIELD_NAME': 'JLH_Kehati',
                'FIELD_TYPE': 0,
                'FIELD_LENGTH': 20,
                'FIELD_PRECISION': 3,
                'NEW_FIELD': False,
                'FORMULA': override_formula,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_final = processing.run("qgis:fieldcalculator", override_params, context=context, feedback=feedback)["OUTPUT"]

            # 4. Membuat Fields (Kolom) sesuai dengan output program yang diperlukan
            fields_to_keep = ['fid','LC','KBA_250','KVA_250','S_EK','S_VE','S_LC','JLH_Kehati','isKK']
            delete_fields = [f for f in source_final.fields().names() if f not in fields_to_keep]
            if delete_fields:
                delete_params = {
                    'INPUT': source_final,
                    'COLUMN': delete_fields,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                }
                source_final = processing.run("qgis:deletecolumn", delete_params, context=context, feedback=feedback)["OUTPUT"]

            # source_final = intersected
            feedback.pushInfo("✅ Semua kriteria override (KK, Savana, Tubuh Air) berhasil diterapkan")

        elif bentuk_output == 'Grid':
            # ==============================
            # Proses untuk output bentuk GRID
            # ==============================
            source_temp = source_calc_jasling

            # 1. Overlay hasil perhitungan JLH_Kehati dengan GRID
            intersection_params = {
                'INPUT': source_temp,
                'OVERLAY': grid,
                'INPUT_FIELDS': [],
                'OVERLAY_FIELDS': ['ID'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_intersect_grid = processing.run("qgis:intersection", intersection_params)["OUTPUT"]

            # 2. Hitung luas poligon hasil overlay
            area_params = {
                'INPUT': source_intersect_grid,
                'FIELD_NAME': 'AREA_POLY_M2',
                'FIELD_TYPE': 0,
                'FIELD_LENGTH': 20,
                'FIELD_PRECISION': 3,
                'NEW_FIELD': True,
                'FORMULA': '$area',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_area_poly = processing.run("qgis:fieldcalculator", area_params)["OUTPUT"]

            # 3. Summarize luas per ID GRID → total AREA_GRID_M2
            summarize_area_params = {
                'INPUT': source_area_poly,
                'CATEGORIES_FIELD_NAME': ['ID'],
                'VALUES_FIELD_NAME': 'AREA_POLY_M2',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            area_by_id = processing.run("qgis:statisticsbycategories", summarize_area_params)["OUTPUT"]

            rename_area_sum_params = {
                'INPUT': area_by_id,
                'FIELD': 'sum',
                'NEW_NAME': 'AREA_GRID_M2',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            area_by_id_renamed = processing.run("qgis:renametablefield", rename_area_sum_params)["OUTPUT"]

            join_area_sum_params = {
                'INPUT': source_area_poly,
                'FIELD': 'ID',
                'INPUT_2': area_by_id_renamed,
                'FIELD_2': 'ID',
                'FIELDS_TO_COPY': ['AREA_GRID_M2'],
                'METHOD': 0,
                'DISCARD_NONMATCHING': False,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_join_area = processing.run("qgis:joinattributestable", join_area_sum_params)["OUTPUT"]

            # 4. Hitung nilai proporsional JLH_Kehati
            proporsional_params = {
                'INPUT': source_join_area,
                'FIELD_NAME': 'JLH_Kehati_Proporsional',
                'FIELD_TYPE': 0,  # Float
                'FIELD_LENGTH': 20,
                'FIELD_PRECISION': 3,
                'NEW_FIELD': True,
                'FORMULA': '"JLH_Kehati" * ("AREA_POLY_M2" / "AREA_GRID_M2")',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_proporsional = processing.run("qgis:fieldcalculator", proporsional_params)["OUTPUT"]

            # 5. Summarize JLH_Kehati_Proporsional per GRID ID
            summarize_params = {
                'INPUT': source_proporsional,
                'CATEGORIES_FIELD_NAME': ['ID'],
                'VALUES_FIELD_NAME': 'JLH_Kehati_Proporsional',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_summarized = processing.run("qgis:statisticsbycategories", summarize_params)["OUTPUT"]

            # 6. Join hasil summarize ke GRID
            join_summarized_params = {
                'INPUT': grid,
                'FIELD': 'ID',
                'INPUT_2': source_summarized,
                'FIELD_2': 'ID',
                'FIELDS_TO_COPY': ['sum'],
                'METHOD': 0,
                'DISCARD_NONMATCHING': False,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_join_summarized = processing.run("qgis:joinattributestable", join_summarized_params)["OUTPUT"]

            # 7. Rename field sum → JLH_Kehati
            rename_params = {
                'INPUT': source_join_summarized,
                'FIELD': 'sum',
                'NEW_NAME': 'JLH_Kehati',
                'OUTPUT': 'memory:'
            }
            source_final = processing.run("qgis:renametablefield", rename_params)["OUTPUT"]

            # 8. Kriteria khusus (KK, Savana, Tubuh Air)
            # 8a. select grid yang beririsan dengan kriteria khusus dan berikan nilai JLH_Kehati = 5
            # Buat spatial index untuk fixed_merged_layer
            index = QgsSpatialIndex(fixed_merged_layer.getFeatures())
            kk_ids = set()
            for grid_feat in source_final.getFeatures():
                if feedback.isCanceled():
                    break
                intersecting_ids = index.intersects(grid_feat.geometry().boundingBox())
                if intersecting_ids:
                    kk_ids.add(grid_feat['ID'])
            # Update nilai JLH_Kehati menjadi 5 untuk grid yang beririsan dengan kriteria khusus
            with edit(source_final):    
                for feat in source_final.getFeatures():
                    if feedback.isCanceled():
                        break
                    if feat['ID'] in kk_ids:
                        feat['JLH_Kehati'] = 5
                        source_final.updateFeature(feat)
            feedback.pushInfo(f"✅ Override JLH_Kehati untuk kriteria khusus berhasil, total grid diubah: {len(kk_ids)}")   

            # 8b. Override JLH_Kehati untuk kriteria Savana dan Tubuh Air
            override_formula = '''
            CASE
                WHEN "KK" = 1 THEN 5
                WHEN "LC" = 'Savana/Padang Rumput' AND "KODE_PROV" IN (51,52,53,91,92,94,95,96) THEN 5
                WHEN "LC" IN ('Tubuh Air','Badan Air') THEN 5
                ELSE "JLH_Kehati"
            END
            '''
            override_params = {
                'INPUT': source_final,
                'FIELD_NAME': 'JLH_Kehati',
                'FIELD_TYPE': 0,
                'FIELD_LENGTH': 20,
                'FIELD_PRECISION': 3,
                'NEW_FIELD': False,
                'FORMULA': override_formula,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_final = processing.run("qgis:fieldcalculator", override_params, context=context, feedback=feedback)["OUTPUT"]

        # Pembulatan Skor Nasional
        if skor_jlh == 'Nasional':
            source = processing.run( "qgis:fieldcalculator", {
                'INPUT': source,  # or iface.activeLayer()
                'FIELD_NAME': 'JLH_Kehati', # Overwrite existing field
                'NEW_FIELD': False,      
                'FORMULA': f"""     round("JLH_Kehati")    """,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT   # or path to file 
            })["OUTPUT"]

        # Kategorisasi JLH_Karbon
        nama_kolom_jlh = 'JLH_Kehati'
        source = processing.run( "qgis:fieldcalculator",
                                    {
                                        'INPUT': source,  # or iface.activeLayer()
                                        'FIELD_NAME': 'Kategori_JLH',
                                        'FIELD_TYPE': 2,        # String
                                        'FIELD_LENGTH': 20,
                                        'NEW_FIELD': True,
                                        'FORMULA': f"""
                                        CASE
                                            WHEN "{nama_kolom_jlh}" >= 1.0 AND "{nama_kolom_jlh}" <= 1.8 THEN 'Sangat Rendah'
                                            WHEN "{nama_kolom_jlh}" > 1.8 AND "{nama_kolom_jlh}" <= 2.6 THEN 'Rendah'
                                            WHEN "{nama_kolom_jlh}" > 2.6 AND "{nama_kolom_jlh}" <= 3.4 THEN 'Sedang'
                                            WHEN "{nama_kolom_jlh}" > 3.4 AND "{nama_kolom_jlh}" <= 4.2 THEN 'Tinggi'
                                            WHEN "{nama_kolom_jlh}" > 4.2 AND "{nama_kolom_jlh}" <= 5.0 THEN 'Sangat Tinggi'
                                            ELSE 'Tidak Diketahui'
                                        END
                                        """,
                                        'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT   # or path to file
                                    }
                                )["OUTPUT"]


        # --- Buat feature sink untuk output akhir ---
        (sink, dest_id) = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            source_final.fields(),
            source_final.wkbType(),
            source_final.sourceCrs()
        )

        total = 100.0 / source_final.featureCount() if source_final.featureCount() else 0
        for current, feature in enumerate(source_final.getFeatures()):
            if feedback.isCanceled():
                break
            sink.addFeature(feature, QgsFeatureSink.FastInsert)
            feedback.setProgress(int(current * total))

        return {self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'JLH Pendukung Habitat dan Kehati'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '02. Indeks Jasa Lingkungan Hidup (IJLH)'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return JLHPendukungKehati()