# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OtomatisasiD3TLH
                                 A QGIS plugin
 Plugin yang membantu pengolahan D3TLH secara otomatis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-15
        copyright            : (C) 2025 by Yayasan Lokahita
        email                : fadillahazhardk@yayasanlokahita.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yayasan Lokahita'
__date__ = '2025-08-15'
__copyright__ = '(C) 2025 by Yayasan Lokahita'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterFeatureSink,
                       QgsVectorLayer,
                       QgsProcessingParameterEnum)
import processing
import os


class JLHPenyediaAir(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    PENUTUP_LAHAN = 'PENUTUP_LAHAN'
    EKOREGION = 'EKOREGION'
    GRID = 'GRID'
    BENTUK_OUTPUT = 'BENTUK_OUTPUT'
    SKOR_JLH = 'SKOR_JLH'
    PULAU = 'PULAU'
    bentuk_output_list = ['Grid', 'Poligon']
    skor_jlh_list = ['Kabupaten/Kota', 'Nasional']
    pulau_list = ['Jawa', 'Sumatera', 'Kalimantan', 'Sulawesi', 'Balinusra', 'Maluku', 'Papua']


    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # Setting untuk pulau
        self.addParameter(
            QgsProcessingParameterEnum(
                self.PULAU,
                self.tr('Pulau'),
                options=self.pulau_list,
                allowMultiple=True,
                defaultValue=[0, 1, 2, 3, 4, 5, 6]  # Default to all options selected
            )
        )

        # Settings for output type
        self.addParameter(
            QgsProcessingParameterEnum(
                self.BENTUK_OUTPUT,
                self.tr('Bentuk Output'),
                options=self.bentuk_output_list,
                defaultValue=1
            )
        )

        # Settings for score type
        self.addParameter(
            QgsProcessingParameterEnum(
                self.SKOR_JLH,
                self.tr('Skor IJLH yang Digunakan'),
                options=self.skor_jlh_list,
                defaultValue=1
            )
        )

        # We add the input vector features source. It can have any kind of
        # geometry.

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.PENUTUP_LAHAN,
                self.tr('Penutup Lahan'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.EKOREGION,
                self.tr('Ekoregion'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.GRID,
                self.tr('Grid'),
                [QgsProcessing.TypeVectorAnyGeometry],
                optional=True
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('JLH Penyedia Air')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        pl = parameters["PENUTUP_LAHAN"]
        ekoregion = parameters["EKOREGION"]
        grid = parameters["GRID"]

        # Penentuan jenis output
        bentuk_output_idx = self.parameterAsEnum(parameters, 'BENTUK_OUTPUT', context)
        bentuk_output = self.bentuk_output_list[bentuk_output_idx]

        # Penentuan jenis skor
        skor_jlh_idx = self.parameterAsEnum(parameters, 'SKOR_JLH', context)
        skor_jlh = self.skor_jlh_list[skor_jlh_idx]

        def joinSkorMatra(source, matra): 
            # Load CSV file containing score values for PL, KBA, and KVA
            match matra.lower():
                case 'kba':
                    skor_file_name = "skor_kba_pya.csv"
                case 'kva':
                    skor_file_name = "skor_kva_pya.csv"
                case 'pl':
                    skor_file_name = "skor_pl_pya.csv"

            if skor_jlh == 'Kabupaten/Kota' and matra.lower() == 'pl':
                csv_path_skor = f"{os.path.dirname(__file__)}/../../data/jlh_pya/kabupaten_kota/{skor_file_name}"  # Update with the actual path to your CSV file
            else:
                csv_path_skor = f"{os.path.dirname(__file__)}/../../data/jlh_pya/{skor_file_name}"  # Update with the actual path to your CSV file
            
            uri_skor = f"file:///{csv_path_skor}?encoding=UTF-8&delimiter=;"

            skor = QgsVectorLayer(uri_skor, "csv_internal", "delimitedtext")

            # Join Skor to the intersection layer
            match matra.lower():
                case 'kba':
                    params = {
                        'INPUT': source,
                        'FIELD': 'KBA_250',
                        'INPUT_2': skor,
                        'FIELD_2': 'EKOREGION',
                        'FIELDS_TO_COPY': ['S_EK'],
                        'METHOD': 0,
                        'DISCARD_NONMATCHING': False,
                        'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                    }
                case 'kva':
                    params = {
                        'INPUT': source,
                        'FIELD': 'KVA_250',
                        'INPUT_2': skor,
                        'FIELD_2': 'VEGETASI',
                        'FIELDS_TO_COPY': ['S_VE'],
                        'METHOD': 0,
                        'DISCARD_NONMATCHING': False,
                        'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                    }
                case 'pl':
                    params = {
                        'INPUT': source,
                        'FIELD': 'LC',
                        'INPUT_2': skor,
                        'FIELD_2': 'LC',
                        'FIELDS_TO_COPY': ['S_LC'],
                        'METHOD': 0,
                        'DISCARD_NONMATCHING': False,
                        'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                    }

            return processing.run("qgis:joinattributestable", params)["OUTPUT"]

        # Intersection of the two layers (Penutup Lahan and Ekoregion (KBA, KVA))
        intersection_params = {
            'INPUT': pl, 
            'OVERLAY': ekoregion,
            'INPUT_FIELDS': ['LC'],
            'OVERLAY_FIELDS': ['KBA_250', 'KVA_250'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }

        source_intersect = processing.run("qgis:intersection", intersection_params)["OUTPUT"]
        
        # Join Skor Matra To Intersection Layer
        source_kba = joinSkorMatra(source_intersect, 'kba')
        source_kva = joinSkorMatra(source_kba, 'kva')
        source_pl = joinSkorMatra(source_kva, 'pl')
        
        # Calcule Jasling  [BOBOT PERLU DIRUBAH UNTUK JLH LAIN]
        bobot_ek = 0.32  # Bobot Ekoregion
        bobot_ve = 0.08  # Bobot Vegetasi
        bobot_lc = 0.6  # Bobot Penutup Lahan

        calculator_params =  {
                'INPUT': source_pl,
                'FIELD_NAME': 'JLH_Air',
                'FIELD_TYPE': 0,             # 0 = Float
                'FIELD_LENGTH': 20,
                'FIELD_PRECISION': 3,
                'NEW_FIELD': True,
                'FORMULA': f'"S_EK" * {bobot_ek} + "S_VE" * {bobot_ve} + "S_LC" * {bobot_lc}',  # multiply three fields
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        source_calc_jasling = processing.run("qgis:fieldcalculator", calculator_params)["OUTPUT"]

        # Proses untuk output bentuk POLIGON atau GRID
        # ============================================================
        if bentuk_output == 'Poligon':
            # Proses untuk output bentuk POLIGON
            # ==============================
            source = source_calc_jasling
            
        elif bentuk_output == 'Grid':
            # Proses untuk output bentuk GRID
            # ==============================
            # Langkah-langkah:
            # 1. Overlay hasil perhitungan JLH_Air dengan GRID
            # 2. Hitung luas poligon hasil overlay
            # 3. Hitung proporsional JLH_Air untuk setiap poligon berdasarkan luasnya
            # 4. Summarize JLH_Air_Proporsional berdasarkan ID GRID
            # 5. Join hasil summarize kembali ke layer GRID

            source_temp = source_calc_jasling

             # Overlay dengan GRID   
            intersection_params = {
                'INPUT': source_temp,
                'OVERLAY': grid,
                'INPUT_FIELDS': [],
                'OVERLAY_FIELDS': ['ID'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_intersect_grid = processing.run("qgis:intersection", intersection_params)["OUTPUT"]

            # Luas poligon hasil overlay
            area_params = {
                'INPUT': source_intersect_grid,
                'FIELD_NAME': 'AREA_POLY_M2',
                'FIELD_TYPE': 0,
                'FIELD_LENGTH': 20,
                'FIELD_PRECISION': 3,
                'NEW_FIELD': True,
                'FORMULA': '$area',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_area_poly = processing.run("qgis:fieldcalculator", area_params)["OUTPUT"]

            # === CHANGED: Hapus perhitungan $area pada layer GRID.
            # Gantikan dengan summarize AREA_POLY_M2 per ID (di source_intersect_grid).
            summarize_area_params = {
                'INPUT': source_area_poly,
                'CATEGORIES_FIELD_NAME': ['ID'],
                'VALUES_FIELD_NAME': 'AREA_POLY_M2',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            area_by_id = processing.run("qgis:statisticsbycategories", summarize_area_params)["OUTPUT"]

            # Ubah nama field 'sum' menjadi 'AREA_GRID_M2'
            rename_area_sum_params = {
                'INPUT': area_by_id,
                'FIELD': 'sum',
                'NEW_NAME': 'AREA_GRID_M2',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            area_by_id_renamed = processing.run("qgis:renametablefield", rename_area_sum_params)["OUTPUT"]

            # Join AREA_GRID_M2 kembali ke potongan poligon hasil overlay
            join_area_sum_params = {
                'INPUT': source_area_poly,
                'FIELD': 'ID',
                'INPUT_2': area_by_id_renamed,
                'FIELD_2': 'ID',
                'FIELDS_TO_COPY': ['AREA_GRID_M2'],
                'METHOD': 0,
                'DISCARD_NONMATCHING': False,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_join_area = processing.run("qgis:joinattributestable", join_area_sum_params)["OUTPUT"]
            # === END CHANGED
            
            # Calculate proporsional JLH_Air for each polygon based on the area
            proporsional_params = {
                'INPUT': source_join_area,
                'FIELD_NAME': 'JLH_Air_Proporsional',
                'FIELD_TYPE': 0,  # 0 = Float
                'FIELD_LENGTH': 20,
                'FIELD_PRECISION': 3,
                'NEW_FIELD': True,
                'FORMULA': '"JLH_Air" * ("AREA_POLY_M2" / "AREA_GRID_M2")',  # Calculate proportional JLH_Air
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_proporsional = processing.run("qgis:fieldcalculator", proporsional_params)["OUTPUT"]

            # Summarize JLH_Air_Proporsional by GRID ID
            summarize_params = {
                'INPUT': source_proporsional,
                'CATEGORIES_FIELD_NAME': ['ID'],
                'VALUES_FIELD_NAME': 'JLH_Air_Proporsional',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_summarized = processing.run("qgis:statisticsbycategories", summarize_params)["OUTPUT"]

            # Join the summarized JLH_Air_Proporsional back to the GRID layer
            join_summarized_params = {
                'INPUT': grid,
                'FIELD': 'ID',
                'INPUT_2': source_summarized,
                'FIELD_2': 'ID',
                'FIELDS_TO_COPY': ['sum'],
                'METHOD': 0,  # 0 = Create separate layer
                'DISCARD_NONMATCHING': False,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            source_join_summarized = processing.run("qgis:joinattributestable", join_summarized_params)["OUTPUT"]

            # Rename the 'sum' field to 'JLH_Air'
            rename_params = {
                'INPUT': source_join_summarized,          # your summarized layer
                'FIELD': 'sum',          # existing field name
                'NEW_NAME': 'JLH_Air',     # new name
                'OUTPUT': 'memory:'
            }
            source_rename_params = processing.run("qgis:renametablefield", rename_params)["OUTPUT"]

            source = source_rename_params

        # Kategorisasi JLH_Air
        if skor_jlh == 'Nasional':
            source = processing.run( "qgis:fieldcalculator", {
                'INPUT': source,  # or iface.activeLayer()
                'FIELD_NAME': 'JLH_Air', # Overwrite existing field
                'NEW_FIELD': False,      
                'FORMULA': f"""     round("JLH_Air")    """,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT   # or path to file 
            })["OUTPUT"]

        # Kategorisasi JLH_Udara
        nama_kolom_jlh = 'JLH_Air'
        source = processing.run( "qgis:fieldcalculator",
                                    {
                                        'INPUT': source,  # or iface.activeLayer()
                                        'FIELD_NAME': 'Kategori_JLH',
                                        'FIELD_TYPE': 2,        # String
                                        'FIELD_LENGTH': 20,
                                        'NEW_FIELD': True,
                                        'FORMULA': f"""
                                        CASE
                                            WHEN "{nama_kolom_jlh}" >= 1.0 AND "{nama_kolom_jlh}" <= 1.8 THEN 'Sangat Rendah'
                                            WHEN "{nama_kolom_jlh}" > 1.8 AND "{nama_kolom_jlh}" <= 2.6 THEN 'Rendah'
                                            WHEN "{nama_kolom_jlh}" > 2.6 AND "{nama_kolom_jlh}" <= 3.4 THEN 'Sedang'
                                            WHEN "{nama_kolom_jlh}" > 3.4 AND "{nama_kolom_jlh}" <= 4.2 THEN 'Tinggi'
                                            WHEN "{nama_kolom_jlh}" > 4.2 AND "{nama_kolom_jlh}" <= 5.0 THEN 'Sangat Tinggi'
                                            ELSE 'Tidak Diketahui'
                                        END
                                        """,
                                        'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT   # or path to file
                                    }
                                )["OUTPUT"]

        # End Proses untuk output bentuk POLIGON atau GRID
        # ============================================================
        # Create a feature sink to store the output
        (sink, dest_id) = self.parameterAsSink(
            parameters, 
            self.OUTPUT,
            context, 
            source.fields(), 
            source.wkbType(), 
            source.sourceCrs()
        )
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break

            # Add a feature in the sink
            sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
            feedback.setProgress(int(current * total))

        return {self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'JLH Penyedia Air'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '02. Indeks Jasa Lingkungan Hidup (IJLH)'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return JLHPenyediaAir()