# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OtomatisasiD3TLH
                                 A QGIS plugin
 Plugin yang membantu pengolahan D3TLH secara otomatis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-15
        copyright            : (C) 2025 by Yayasan Lokahita
        email                : fadillahazhardk@yayasanlokahita.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yayasan Lokahita'
__date__ = '2025-08-15'
__copyright__ = '(C) 2025 by Yayasan Lokahita'

# This will get replaced with a git SHA1 when you do a git archive
__revision__ = '$Format:%H$'

import os
from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (
    QgsProcessing,
    QgsFeatureSink,
    QgsProcessingAlgorithm,
    QgsProcessingException,
    QgsProcessingParameterEnum,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFeatureSink,
    QgsVectorLayer
)
import processing

class JLHPenyediaPangan(QgsProcessingAlgorithm):
    """
    02. Indeks Jasa Lingkungan Hidup (IJLH) – JLH Penyedia Pangan
    """

    # Parameter keys
    OUTPUT = 'OUTPUT'
    PENUTUP_LAHAN = 'PENUTUP_LAHAN'
    EKOREGION = 'EKOREGION'
    GRID = 'GRID'
    OUTPUT_TYPE = ['Grid', 'Poligon']

    def initAlgorithm(self, config):
        # Dropdown pulau (khusus skor PL)
        self.addParameter(
            QgsProcessingParameterEnum(
                'ISLAND',
                self.tr('Pulau (khusus skor PL pada JLH penyedia pangan)'),
                options=['Jawa', 'Sumatera', 'Kalimantan', 'Sulawesi', 'Papua', 'Bali–Nusra', 'Maluku'],
                defaultValue=0
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.PENUTUP_LAHAN,
                self.tr('Penutup Lahan'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.EKOREGION,
                self.tr('Ekoregion'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.GRID,
                self.tr('Grid'),
                [QgsProcessing.TypeVectorAnyGeometry],
                optional=True
            )
        )

        # Opsi Untuk Output ke Versi Grid Atau Tidak
        self.addParameter(
            QgsProcessingParameterEnum(
                'BENTUK_OUTPUT',
                self.tr('Bentuk Output'),
                options=self.OUTPUT_TYPE,
                defaultValue=0
            )
        )

        # Opsi Untuk Output ke Versi Grid Atau Tidak
        self.addParameter(
            QgsProcessingParameterEnum(
                'BENTUK_OUTPUT',
                self.tr('Bentuk Output'),
                options=self.OUTPUT_TYPE,
                defaultValue=0
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('JLH Penyedia Pangan')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        # Input layers
        pl = parameters[self.PENUTUP_LAHAN]
        ekoregion = parameters[self.EKOREGION]
        grid = parameters[self.GRID]

        # Pulau untuk skor PL
        island_idx = self.parameterAsEnum(parameters, 'ISLAND', context)
        _islands = ['Jawa', 'Sumatera', 'Kalimantan', 'Sulawesi', 'Papua', 'Bali–Nusra', 'Maluku']
        island = _islands[island_idx]

        # Bentuk output
        output_type = self.parameterAsEnum(parameters, self.OUTPUT_TYPE, context)  # 0=Grid, 1=Polygon

        # ==== Lokasi CSV: dari ROOT plugin (…/otomatisasi_d3tlh/data/jlh_pp) ====
        this_file   = os.path.abspath(__file__)
        plugin_root = os.path.dirname(os.path.dirname(os.path.dirname(this_file)))
        data_root   = os.path.join(plugin_root, "data", "jlh_pp")

        # Helper: load CSV sebagai QgsVectorLayer delimitedtext (coba ; lalu ,)
        def load_csv_table(csv_abs_path: str, name: str) -> QgsVectorLayer:
            csv_abs_path = os.path.normpath(csv_abs_path)
            for delim in (';', ','):
                uri = f"file:///{csv_abs_path}?encoding=UTF-8&delimiter={delim}&geomType=none"
                lyr = QgsVectorLayer(uri, name, "delimitedtext")
                if lyr.isValid():
                    return lyr
            raise QgsProcessingException(self.tr(f'CSV tidak valid atau tidak ditemukan: {csv_abs_path}'))

        # Helper: join skor per-matra dari CSV ke layer 'source'
        def joinSkorMatra(source, matra):
            mat = matra.lower()
            if mat == 'kba':
                # JOIN: KBA_250 (layer) -> EKOREGION (CSV)
                skor_file_name = 'skor_ekoregion_jlh_penyedia_pangan.csv'
                left_field, right_field = 'KBA_250', 'EKOREGION'
            elif mat == 'kva':
                # JOIN: KVA_250 (layer) -> VEGETASI (CSV)
                skor_file_name = 'skor_vegetasi_jlh_penyedia_pangan.csv'
                left_field, right_field = 'KVA_250', 'VEGETASI'
            elif mat == 'pl':
                filename_map = {
                    'Jawa':       'skor_pl_jlh_penyedia_pangan_jawa.csv',
                    'Sumatera':   'skor_pl_jlh_penyedia_pangan_sumatera.csv',
                    'Kalimantan': 'skor_pl_jlh_penyedia_pangan_kalimantan.csv',
                    'Sulawesi':   'skor_pl_jlh_penyedia_pangan_sulawesi.csv',
                    'Papua':      'skor_pl_jlh_penyedia_pangan_papua.csv',
                    'Bali–Nusra': 'skor_pl_jlh_penyedia_pangan_balinustra.csv',
                    'Maluku':     'skor_pl_jlh_penyedia_pangan_maluku.csv',
                }
                if island not in filename_map:
                    raise QgsProcessingException(f"Pulau tidak dikenal untuk skor PL: {island}")
                skor_file_name = filename_map[island]
                left_field, right_field = 'LC', 'LC'
            else:
                raise QgsProcessingException(f"Matra tidak dikenal: {matra}")

            csv_path_skor = os.path.join(data_root, skor_file_name)
            skor_layer = load_csv_table(csv_path_skor, f'skor_{mat}')
            joined = processing.run(
                "qgis:joinattributestable",
                {
                    'INPUT': source,
                    'FIELD': left_field,
                    'INPUT_2': skor_layer,
                    'FIELD_2': right_field,
                    'FIELDS_TO_COPY': [],   # ambil semua kolom skor
                    'METHOD': 0,
                    'DISCARD_NONMATCHING': False,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                },
                context=context, feedback=feedback
            )["OUTPUT"]
            return joined

        # 1) Overlay PL × Ekoregion (bawa field kunci untuk join skor)
        inter = processing.run(
            "qgis:intersection",
            {
                'INPUT': pl,
                'OVERLAY': ekoregion,
                'INPUT_FIELDS': ['LC'],
                'OVERLAY_FIELDS': ['KBA_250', 'KVA_250'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # 2) Join skor KBA, KVA, PL
        src_kba = joinSkorMatra(inter, 'kba')
        src_kva = joinSkorMatra(src_kba, 'kva')
        src_pl  = joinSkorMatra(src_kva, 'pl')

        # 3) Hitung indeks JLH_Pangan
        bobot_ek = 0.28
        bobot_ve = 0.12
        bobot_lc = 0.60
        src_idx = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': src_pl,
                'FIELD_NAME': 'JLH_Pangan',
                'FIELD_TYPE': 0,
                'FIELD_LENGTH': 20,
                'FIELD_PRECISION': 3,
                'NEW_FIELD': True,
                'FORMULA': f'"S_EK" * {bobot_ek} + "S_VE" * {bobot_ve} + "S_LC" * {bobot_lc}',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # === CABANG OUTPUT ===
        if self.OUTPUT_TYPE == 'Poligon':
            # -------- Polygon mode: tampilkan kolom yang diminta --------
            keep_cols = processing.run(
                "qgis:refactorfields",
                {
                    "INPUT": src_idx,
                    "FIELDS_MAPPING": [
                        {"expression": '"EKOREGION"', "length": 254, "name": "EKOREGION", "precision": 0, "type": QVariant.String},
                        {"expression": '"VEGETASI"',  "length": 254, "name": "VEGETASI",  "precision": 0, "type": QVariant.String},
                        {"expression": '"LC"',        "length": 254, "name": "LC",        "precision": 0, "type": QVariant.String},
                        {"expression": '"S_EK"',      "length": 0,  "name": "S_EK",      "precision": 0, "type": QVariant.Double},
                        {"expression": '"S_VE"',      "length": 0,  "name": "S_VE",      "precision": 0, "type": QVariant.Double},
                        {"expression": '"S_LC"',      "length": 0,  "name": "S_LC",      "precision": 0, "type": QVariant.Double},
                        {"expression": '"JLH_Pangan"', "length": 0, "name": "JLH_Pangan","precision": 0, "type": QVariant.Double},
                    ],
                    "OUTPUT": QgsProcessing.TEMPORARY_OUTPUT,
                },
                context=context, feedback=feedback
            )["OUTPUT"]
            final_layer = keep_cols

        else:
            # -------- Grid mode (default) --------
            inter_grid = processing.run(
                "qgis:intersection",
                {
                    'INPUT': src_idx,
                    'OVERLAY': grid,
                    'INPUT_FIELDS': [],
                    'OVERLAY_FIELDS': ['ID'],
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                },
                context=context, feedback=feedback
            )["OUTPUT"]

            area_poly = processing.run(
                "qgis:fieldcalculator",
                {
                    'INPUT': inter_grid,
                    'FIELD_NAME': 'AREA_POLY_M2',
                    'FIELD_TYPE': 0,
                    'FIELD_LENGTH': 20,
                    'FIELD_PRECISION': 3,
                    'NEW_FIELD': True,
                    'FORMULA': '$area',
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                },
                context=context, feedback=feedback
            )["OUTPUT"]

            area_by_id = processing.run(
                "qgis:statisticsbycategories",
                {
                    'INPUT': area_poly,
                    'CATEGORIES_FIELD_NAME': ['ID'],
                    'VALUES_FIELD_NAME': 'AREA_POLY_M2',
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                },
                context=context, feedback=feedback
            )["OUTPUT"]

            area_by_id_renamed = processing.run(
                "qgis:renametablefield",
                {
                    'INPUT': area_by_id,
                    'FIELD': 'sum',
                    'NEW_NAME': 'AREA_GRID_M2',
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                },
                context=context, feedback=feedback
            )["OUTPUT"]

            inter_grid_with_area = processing.run(
                "qgis:joinattributestable",
                {
                    'INPUT': area_poly,
                    'FIELD': 'ID',
                    'INPUT_2': area_by_id_renamed,
                    'FIELD_2': 'ID',
                    'FIELDS_TO_COPY': ['AREA_GRID_M2'],
                    'METHOD': 0,
                    'DISCARD_NONMATCHING': False,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                },
                context=context, feedback=feedback
            )["OUTPUT"]

            prop = processing.run(
                "qgis:fieldcalculator",
                {
                    'INPUT': inter_grid_with_area,
                    'FIELD_NAME': 'JLH_Pangan_Proporsional',
                    'FIELD_TYPE': 0,
                    'FIELD_LENGTH': 20,
                    'FIELD_PRECISION': 3,
                    'NEW_FIELD': True,
                    'FORMULA': '"JLH_Pangan" * ("AREA_POLY_M2" / "AREA_GRID_M2")',
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                },
                context=context, feedback=feedback
            )["OUTPUT"]

            summed = processing.run(
                "qgis:statisticsbycategories",
                {
                    'INPUT': prop,
                    'CATEGORIES_FIELD_NAME': ['ID'],
                    'VALUES_FIELD_NAME': 'JLH_Pangan_Proporsional',
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                },
                context=context, feedback=feedback
            )["OUTPUT"]

            # Join 'sum' ke GRID lalu rename ke JLH_Pangan
            grid_join = processing.run(
                "qgis:joinattributestable",
                {
                    'INPUT': grid,
                    'FIELD': 'ID',
                    'INPUT_2': summed,
                    'FIELD_2': 'ID',
                    'FIELDS_TO_COPY': ['sum'],
                    'METHOD': 0,
                    'DISCARD_NONMATCHING': False,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                },
                context=context, feedback=feedback
            )["OUTPUT"]

            final_layer = processing.run(
                "qgis:renametablefield",
                {
                    'INPUT': grid_join,
                    'FIELD': 'sum',
                    'NEW_NAME': 'JLH_Pangan',
                    'OUTPUT': 'memory:'
                },
                context=context, feedback=feedback
            )["OUTPUT"]

        # Tulis ke sink
        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context,
            final_layer.fields(), final_layer.wkbType(), final_layer.sourceCrs()
        )

        total = 100.0 / final_layer.featureCount() if final_layer.featureCount() else 0
        for current, feature in enumerate(final_layer.getFeatures()):
            if feedback.isCanceled():
                break
            sink.addFeature(feature, QgsFeatureSink.FastInsert)
            feedback.setProgress(int(current * total))

        return {self.OUTPUT: dest_id}

    def name(self):
        return 'JLH Penyedia Pangan'

    def displayName(self):
        return self.tr(self.name())

    def group(self):
        return self.tr(self.groupId())

    def groupId(self):
        return '02. Indeks Jasa Lingkungan Hidup (IJLH)'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return JLHPenyediaPangan()
