# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OtomatisasiD3TLH
                                 A QGIS plugin
 Plugin yang membantu pengolahan D3TLH secara otomatis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-15
        copyright            : (C) 2025 by Yayasan Lokahita
        email                : fadillahazhardk@yayasanlokahita.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yayasan Lokahita'
__date__ = '2025-08-15'
__copyright__ = '(C) 2025 by Yayasan Lokahita'

# This will get replaced with a git SHA1 when you do a git archive
__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    QgsProcessing,
    QgsFeatureSink,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFeatureSink,
    QgsVectorLayer,
    QgsProcessingParameterEnum,
    QgsProcessingException
)
import processing
import os


class JLHPenyediaPangan(QgsProcessingAlgorithm):
    """
    JLH Penyedia Pangan
    """

    OUTPUT = 'OUTPUT'
    PENUTUP_LAHAN = 'PENUTUP_LAHAN'
    EKOREGION = 'EKOREGION'
    GRID = 'GRID'

    def initAlgorithm(self, config):
        # Dropdown pulau (khusus skor PL)
        self.addParameter(
            QgsProcessingParameterEnum(
                'ISLAND',
                self.tr('Pulau (khusus skor PL pada JLH penyedia pangan)'),
                options=['Jawa', 'Sumatera', 'Kalimantan', 'Sulawesi', 'Papua', 'Bali_Nusa', 'Maluku'],
                defaultValue=0
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.PENUTUP_LAHAN,
                self.tr('Penutup Lahan'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.EKOREGION,
                self.tr('Ekoregion'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.GRID,
                self.tr('GRID'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('JLH Penyedia Pangan')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        pl = parameters["PENUTUP_LAHAN"]
        ekoregion = parameters["EKOREGION"]
        grid = parameters["GRID"]

        # Ambil pilihan pulau dari dropdown
        island_idx = self.parameterAsEnum(parameters, 'ISLAND', context)
        _islands = ['Jawa', 'Sumatera', 'Kalimantan', 'Sulawesi', 'Papua', 'Bali_Nusa', 'Maluku']
        island = _islands[island_idx]

        def joinSkorMatra(source, matra):
            mat = matra.lower()

            # Tentukan nama file skor sesuai matra
            if mat == 'kba':
                skor_file_name = "skor_ekoregion_jlh_penyedia_pangan.csv"
            elif mat == 'kva':
                skor_file_name = "skor_vegetasi_jlh_penyedia_pangan.csv"
            elif mat == 'pl':
                filename_map = {
                    'Jawa':       'skor_pl_jlh_penyedia_pangan_jawa.csv',
                    'Sumatera':   'skor_pl_jlh_penyedia_pangan_sumatera.csv',
                    'Kalimantan': 'skor_pl_jlh_penyedia_pangan_kalimantan.csv',
                    'Sulawesi':   'skor_pl_jlh_penyedia_pangan_sulawesi.csv',
                    'Papua':      'skor_pl_jlh_penyedia_pangan_papua.csv',
                    'Bali_Nusa':  'skor_pl_jlh_penyedia_pangan_bali_nusa.csv',
                    'Maluku':     'skor_pl_jlh_penyedia_pangan_maluku.csv',
                }
                try:
                    skor_file_name = filename_map[island]
                except KeyError:
                    raise QgsProcessingException(f"Pulau tidak dikenal untuk skor PL: {island}")
            else:
                raise QgsProcessingException(f"Matra tidak dikenal: {matra}")

            # Path CSV di direktori data yang sama
            csv_path_skor = os.path.join(os.path.dirname(__file__), "..", "..", "data", "jlh_pp", skor_file_name)
            uri_skor = f"file:///{csv_path_skor}?encoding=UTF-8&delimiter=;"

            skor = QgsVectorLayer(uri_skor, "csv_internal", "delimitedtext")
            if not skor.isValid():
                raise QgsProcessingException(f"CSV tidak valid atau tidak ditemukan: {csv_path_skor}")

            # Parameter join
            if mat == 'kba':
                params = {
                    'INPUT': source,
                    'FIELD': 'KBA_250',
                    'INPUT_2': skor,
                    'FIELD_2': 'EKOREGION',
                    'FIELDS_TO_COPY': ['S_EK'],
                    'METHOD': 0,
                    'DISCARD_NONMATCHING': False,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                }
            elif mat == 'kva':
                params = {
                    'INPUT': source,
                    'FIELD': 'KVA_250',
                    'INPUT_2': skor,
                    'FIELD_2': 'VEGETASI',
                    'FIELDS_TO_COPY': ['S_VE'],
                    'METHOD': 0,
                    'DISCARD_NONMATCHING': False,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                }
            else:  # pl
                params = {
                    'INPUT': source,
                    'FIELD': 'LC',
                    'INPUT_2': skor,
                    'FIELD_2': 'LC',
                    'FIELDS_TO_COPY': ['S_LC'],
                    'METHOD': 0,
                    'DISCARD_NONMATCHING': False,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                }

            return processing.run("qgis:joinattributestable", params)["OUTPUT"]

        # Intersection PL × Ekoregion (bawa LC, KBA_250, KVA_250)
        intersection_params = {
            'INPUT': pl,
            'OVERLAY': ekoregion,
            'INPUT_FIELDS': ['LC'],
            'OVERLAY_FIELDS': ['KBA_250', 'KVA_250'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        source_intersect = processing.run("qgis:intersection", intersection_params)["OUTPUT"]

        # Join skor
        source_kba = joinSkorMatra(source_intersect, 'kba')
        source_kva = joinSkorMatra(source_kba, 'kva')
        source_pl = joinSkorMatra(source_kva, 'pl')

        # Hitung indeks
        bobot_ek = 0.28
        bobot_ve = 0.12
        bobot_lc = 0.6

        calculator_params = {
            'INPUT': source_pl,
            'FIELD_NAME': 'JLH_Pangan',
            'FIELD_TYPE': 0,
            'FIELD_LENGTH': 20,
            'FIELD_PRECISION': 3,
            'NEW_FIELD': True,
            'FORMULA': f'"S_EK" * {bobot_ek} + "S_VE" * {bobot_ve} + "S_LC" * {bobot_lc}',
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        source_calc_jasling = processing.run("qgis:fieldcalculator", calculator_params)["OUTPUT"]

        # Overlay dengan GRID
        intersection_params = {
            'INPUT': source_calc_jasling,
            'OVERLAY': grid,
            'INPUT_FIELDS': [],
            'OVERLAY_FIELDS': ['ID'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        source_intersect_grid = processing.run("qgis:intersection", intersection_params)["OUTPUT"]

        # Luas poligon hasil overlay
        area_params = {
            'INPUT': source_intersect_grid,
            'FIELD_NAME': 'AREA_POLY_M2',
            'FIELD_TYPE': 0,
            'FIELD_LENGTH': 20,
            'FIELD_PRECISION': 3,
            'NEW_FIELD': True,
            'FORMULA': '$area',
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        source_area_poly = processing.run("qgis:fieldcalculator", area_params)["OUTPUT"]

        # === CHANGED: Hapus perhitungan $area pada layer GRID.
        # Gantikan dengan summarize AREA_POLY_M2 per ID (di source_intersect_grid).
        summarize_area_params = {
            'INPUT': source_area_poly,
            'CATEGORIES_FIELD_NAME': ['ID'],
            'VALUES_FIELD_NAME': 'AREA_POLY_M2',
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        area_by_id = processing.run("qgis:statisticsbycategories", summarize_area_params)["OUTPUT"]

        # Ubah nama field 'sum' menjadi 'AREA_GRID_M2'
        rename_area_sum_params = {
            'INPUT': area_by_id,
            'FIELD': 'sum',
            'NEW_NAME': 'AREA_GRID_M2',
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        area_by_id_renamed = processing.run("qgis:renametablefield", rename_area_sum_params)["OUTPUT"]

        # Join AREA_GRID_M2 kembali ke potongan poligon hasil overlay
        join_area_sum_params = {
            'INPUT': source_area_poly,
            'FIELD': 'ID',
            'INPUT_2': area_by_id_renamed,
            'FIELD_2': 'ID',
            'FIELDS_TO_COPY': ['AREA_GRID_M2'],
            'METHOD': 0,
            'DISCARD_NONMATCHING': False,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        source_join_area = processing.run("qgis:joinattributestable", join_area_sum_params)["OUTPUT"]
        # === END CHANGED

        # Proporsional JLH_Pangan
        proporsional_params = {
            'INPUT': source_join_area,
            'FIELD_NAME': 'JLH_Pangan_Proporsional',
            'FIELD_TYPE': 0,
            'FIELD_LENGTH': 20,
            'FIELD_PRECISION': 3,
            'NEW_FIELD': True,
            'FORMULA': '"JLH_Pangan" * ("AREA_POLY_M2" / "AREA_GRID_M2")',
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        source_proporsional = processing.run("qgis:fieldcalculator", proporsional_params)["OUTPUT"]

        # Agregasi per ID GRID
        summarize_params = {
            'INPUT': source_proporsional,
            'CATEGORIES_FIELD_NAME': ['ID'],
            'VALUES_FIELD_NAME': 'JLH_Pangan_Proporsional',
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        source_summarized = processing.run("qgis:statisticsbycategories", summarize_params)["OUTPUT"]

        # Join balik ke GRID
        join_summarized_params = {
            'INPUT': grid,
            'FIELD': 'ID',
            'INPUT_2': source_summarized,
            'FIELD_2': 'ID',
            'FIELDS_TO_COPY': ['sum'],
            'METHOD': 0,
            'DISCARD_NONMATCHING': False,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        source_join_summarized = processing.run("qgis:joinattributestable", join_summarized_params)["OUTPUT"]

        # Rename field
        rename_params = {
            'INPUT': source_join_summarized,
            'FIELD': 'sum',
            'NEW_NAME': 'IJE_Pangan',
            'OUTPUT': 'memory:'
        }
        source = processing.run("qgis:renametablefield", rename_params)["OUTPUT"]

        # Output sink
        (sink, dest_id) = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            source.fields(),
            source.wkbType(),
            source.sourceCrs()
        )

        total = 100.0 / source.featureCount() if source.featureCount() else 0
        for current, feature in enumerate(source.getFeatures()):
            if feedback.isCanceled():
                break
            sink.addFeature(feature, QgsFeatureSink.FastInsert)
            feedback.setProgress(int(current * total))

        return {self.OUTPUT: dest_id}

    def name(self):
        return 'JLH Penyedia Pangan'

    def displayName(self):
        return self.tr(self.name())

    def group(self):
        return self.tr(self.groupId())

    def groupId(self):
        return '02. Indeks Jasa Lingkungan Hidup (IJLH)'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return JLHPenyediaPangan()
