# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OtomatisasiD3TLH
                                 A QGIS plugin
 Plugin yang membantu pengolahan D3TLH secara otomatis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-15
        copyright            : (C) 2025 by Yayasan Lokahita
        email                : fadillahazhardk@yayasanlokahita.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yayasan Lokahita'
__date__ = '2025-08-15'
__copyright__ = '(C) 2025 by Yayasan Lokahita'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterVectorLayer)

import processing
import os

class IntegrationIKPAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    IKP_Air = 'IKP_Air'
    IKP_Udara = 'IKP_Udara'
    IKP_Lahan = 'IKP_Lahan'
    IKP_Kehati = 'IKP_Kehati'
    IKP_Laut = 'IKP_Lauts'
    IKP_Integrasi = 'IKP_Integrasi'

    BOBOT_IKP_Air = 0.49
    BOBOT_IKP_Lahan = 0.29
    BOBOT_Kehati = 0.14
    BOBOT_Udara = 0.08

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.IKP_Udara,
                self.tr('Data Indeks Kesesuaian Pemukiman Udara'),
                [QgsProcessing.TypeVectorAnyGeometry],
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.IKP_Air,
                self.tr('Data Indeks Kesesuaian Pemukiman Air'),
                [QgsProcessing.TypeVectorAnyGeometry],
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.IKP_Lahan,
                self.tr('Data Indeks Kesesuaian Pemukiman Lahan'),
                [QgsProcessing.TypeVectorAnyGeometry],
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.IKP_Kehati,
                self.tr('Data Indeks Kesesuaian Pemukiman Kehati'),
                [QgsProcessing.TypeVectorAnyGeometry],
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.IKP_Laut,
                self.tr('Data Indeks Kesesuaian Pemukiman Laut'),
                optional=True
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.IKP_Integrasi,
                self.tr('Integrasi IKP')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        # DATA INPUT
        ikp_air = self.parameterAsVectorLayer(parameters, self.IKP_Air, context)
        ikp_lahan = self.parameterAsVectorLayer(parameters, self.IKP_Lahan, context)
        ikp_kehati = self.parameterAsVectorLayer(parameters, self.IKP_Kehati, context)
        ikp_udara = self.parameterAsVectorLayer(parameters, self.IKP_Udara, context)

        # 1. Integrasi semua data menjadi satu
        ikplh1 = processing.run(
            "qgis:joinattributestable",
            {
                    'INPUT': ikp_air,
                    'FIELD': 'ID',
                    'INPUT_2': ikp_lahan,
                    'FIELD_2': 'ID',
                    'FIELDS_TO_COPY': [f'PPK_{1}'], # OUTPUT ?
                    'METHOD': 0,
                    'DISCARD_NONMATCHING': False,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        ikplh2 = processing.run(
            "qgis:joinattributestable",
            {
                    'INPUT': ikplh1,
                    'FIELD': 'ID',
                    'INPUT_2': ikp_kehati,
                    'FIELD_2': 'ID',
                    'FIELDS_TO_COPY': [f'PPK_{1}'], # OUTPUT ?
                    'METHOD': 0,
                    'DISCARD_NONMATCHING': False,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        ikplh3 = processing.run(
            "qgis:joinattributestable",
            {
                    'INPUT': ikplh2,
                    'FIELD': 'ID',
                    'INPUT_2': ikp_udara,
                    'FIELD_2': 'ID',
                    'FIELDS_TO_COPY': [f'PPK_{1}'], # OUTPUT ?
                    'METHOD': 0,
                    'DISCARD_NONMATCHING': False,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]
        
        ikplh_final = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': ikplh3,
                'FIELD_NAME': 'IKPLH',
                'FIELD_TYPE': 0,  # Decimal number (real)
                'FIELD_LENGTH': 10,
                'FIELD_PRECISION': 2,
                'NEW_FIELD': True,
                'FORMULA': f'( "IKU_Air" + "IKU_Lahan" + "IKU_Udara" + "IKU_Kehati" ) / 4', # OUTPUT ?
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        kelas_ikplh = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': ikplh_final,
                'FIELD_NAME': 'KLS_IKPLH',
                'FIELD_TYPE': 1,  # Text (string),
                'FIELD_LENGTH': 20,
                'NEW_FIELD': True,
                'FORMULA': '''
                CASE
                    WHEN "IKPLH" <= 1.8 THEN 1
                    WHEN "IKPLH" > 1.8 AND "IKPLH" <= 2.6 THEN 2
                    WHEN "IKPLH" > 2.6 AND "IKPLH" <= 3.4 THEN 3
                    WHEN "IKPLH" > 3.4 AND "IKPLH" <= 4.2 THEN 4
                    WHEN "IKPLH" > 4.2 THEN 5
                    ELSE 0
                END
                ''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        final_layer = kelas_ikplh
        (sink, dest_id) = self.parameterAsSink(
            parameters,
            self.PENUTUP_LAHAN_FIX,
            context,
            final_layer.fields(),
            final_layer.wkbType(),
            final_layer.sourceCrs()
        )
        features = final_layer.getFeatures()
        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break

            # Add a feature in the sink
            sink.addFeature(feature, QgsFeatureSink.FastInsert)

        return {self.IKP_Integrasi: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'integration'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('Integrasi IKP')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'F. Integration'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return IntegrationIKPAlgorithm()
