# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OtomatisasiD3TLH
                                 A QGIS plugin
 Plugin yang membantu pengolahan D3TLH secara otomatis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-15
        copyright            : (C) 2025 by Yayasan Lokahita
        email                : fadillahazhardk@yayasanlokahita.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yayasan Lokahita'
__date__ = '2025-08-15'
__copyright__ = '(C) 2025 by Yayasan Lokahita'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingProvider

# Algoritma Pre-Processing
from .pre_processing_algs.pengecekan_kualitas_data_algorithm import PengecekanKualitasData
from .pre_processing_algs.pulau_algorithm import AddPulauFieldAlgorithm
from .pre_processing_algs.standarisasi_skema_data_algorithm import StandarisasiSkemaData

# Algoritma IJLH
from .ijlh_algs.jlh_pengatur_kualitas_udara_algorithm import JLHPengaturKualitasUdara
from .ijlh_algs.jlh_penyedia_air_algorithm import JLHPenyediaAir
from .ijlh_algs.jlh_penyedia_pangan_algorithm import JLHPenyediaPangan
from .ijlh_algs.jlh_penyerapan_dan_penyimpanan_karbon_algorithm import JLHPenyerapanDanPenyimpananKarbon
from .ijlh_algs.jlh_pendukung_habibat_dan_kehati_algorithm import JLHPendukungKehati
from .ijlh_algs.jlh_pengaturan_air_algorithm import JLHPengaturanAir

from .ikp_algs.indeks_kemampuan_pemanfaatan_lahan_algorithm import IKPLahanAlgorithm

from .pop_algs.distribusi_penduduk_algorithm import DistribusiPendudukSGSRI

# Algoritma IKP
from .ikp_algs.indeks_kemampuan_pemanfaatan_kehati_algorithm import IndeksKemampuanPemanfaatanKehati
from .ikp_algs.indeks_kemampuan_pemanfaatan_udara_algorithm import IKPUdaraAlgorithm

# Algoritma lainnya
from .utils_algs.mca_polygon_algorithms import MCA_GRID_Poligon_Algoritm
from .utils_algs.grid_algorithm import GridIndonesiaAlgorithm
from .utils_algs.klasifikasi_jalan_algorithm import StandarisasiKelasJalanInteractiveAlgorithm
from .utils_algs.klasifikasi_pl_kwshutan_algorithm import KlasifikasiPLatauKawasanHutan

class OtomatisasiD3TLHProvider(QgsProcessingProvider):

    def __init__(self):
        """
        Default constructor.
        """
        QgsProcessingProvider.__init__(self)

    def unload(self):
        """
        Unloads the provider. Any tear-down steps required by the provider
        should be implemented here.
        """
        pass

    def loadAlgorithms(self):
        """
        Loads all algorithms belonging to this provider.
        """
        # Algoritma Pre-Processing
        self.addAlgorithm(PengecekanKualitasData())
        self.addAlgorithm(AddPulauFieldAlgorithm())
        self.addAlgorithm(StandarisasiSkemaData())

        # Algoritma IJLH
        self.addAlgorithm(JLHPengaturKualitasUdara())
        self.addAlgorithm(JLHPenyediaAir())
        self.addAlgorithm(JLHPenyediaPangan())
        self.addAlgorithm(JLHPenyerapanDanPenyimpananKarbon())
        self.addAlgorithm(JLHPendukungKehati())
        self.addAlgorithm(JLHPengaturanAir())
        
        # Algoritma IKP
        self.addAlgorithm(DistribusiPendudukSGSRI())
        self.addAlgorithm(IndeksKemampuanPemanfaatanKehati())
        self.addAlgorithm(IKPLahanAlgorithm())
        self.addAlgorithm(IKPUdaraAlgorithm())

        # Algoritma lainnya
        self.addAlgorithm(MCA_GRID_Poligon_Algoritm())
        self.addAlgorithm(GridIndonesiaAlgorithm())
        self.addAlgorithm(StandarisasiKelasJalanInteractiveAlgorithm())
        self.addAlgorithm(KlasifikasiPLatauKawasanHutan())


    def id(self):
        """
        Returns the unique provider id, used for identifying the provider. This
        string should be a unique, short, character only string, eg "qgis" or
        "gdal". This string should not be localised.
        """
        return 'd3tlh'

    def name(self):
        """
        Returns the provider name, which is used to describe the provider
        within the GUI.

        This string should be short (e.g. "Lastools") and localised.
        """
        return self.tr('Otomatisasi D3TLH')

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        return QgsProcessingProvider.icon(self)

    def longName(self):
        """
        Returns the a longer version of the provider name, which can include
        extra details such as version numbers. E.g. "Lastools LIDAR tools
        (version 2.2.1)". This string should be localised. The default
        implementation returns the same string as name().
        """
        return self.name()
