# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OtomatisasiD3TLH
                                 A QGIS plugin
 Plugin yang membantu pengolahan D3TLH secara otomatis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-15
        copyright            : (C) 2025 by Yayasan Lokahita
        email                : fadillahazhardk@yayasanlokahita.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yayasan Lokahita'
__date__ = '2025-08-15'
__copyright__ = '(C) 2025 by Yayasan Lokahita'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterString,
                       QgsCoordinateReferenceSystem
                       )

import processing, os

class IKPKehatiAlgorithm(QgsProcessingAlgorithm):
    # Parameters BCPI
    GRID_PGA = 'GRID_PGA'
    GRID_PPK = 'GRID_PPK'
    GRID_PGN = 'GRID_PGN'
    GRID_PHK = 'GRID_PHK'
    # Parameters BI
    EKOREGION = 'EKOREGION'
    TAHUN = 'TAHUN'
    PL = 'PL'
    GRID = 'GRID'
    HABITAT = 'HABITAT'
    RTE = 'RTE'
    WILAYAH_EKOREGION = 'WILAYAH_EKOREGION'

    # Output
    OUTPUT = 'OUTPUT'

    def initAlgorithm(self, config):
        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.GRID,
                self.tr('Data Grid'),
                optional=True,
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.GRID_PGA,
                self.tr('GRID JLH Pengaturan Air [Dengan Kolom "PGA_XX_KK", XX adalah dua digit terakhir tahun.]'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.GRID_PHK,
                self.tr('GRID JLH Kehati [Dengan Kolom "PHK_XX_KK", XX adalah dua digit terakhir tahun.]'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.GRID_PPK,
                self.tr('GRID JLH Karbon [Dengan Kolom "PPK_XX", XX adalah dua digit terakhir tahun.]'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.GRID_PGN,
                self.tr('GRID JLH Penyedia Pangan [Dengan Kolom "PGN_XX", XX adalah dua digit terakhir tahun.]'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.TAHUN,
                self.tr('Tahun Penutup Lahan'),
                defaultValue=2024
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.PL,
                self.tr('Data Penutup Lahan [Dengan Kolom "PL"]'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.EKOREGION,
                self.tr('Data Unit Ekoregion [Dengan kolom "KBA_250" dan "KVA_250"]'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )
                
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.WILAYAH_EKOREGION,
                self.tr('Wilayah Ekoregion [Dengan nama kolom "NAMA_WE"]'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.HABITAT,
                self.tr('Data Tipe Habitat IUCN [Dengan nama kolom "KLS_HAB_KK"]'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.RTE,
                self.tr('Data RTE IUCN [Dengan nama kolom "KLS_RTE"]'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('IKP Kehati [kolom "KLS_KONDI"]')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        # Tahun Penutup Lahan
        year = self.parameterAsString(parameters, self.TAHUN, context)
        year = year[-2:]

        # Parameters BCPI
        grid_pga = parameters[self.GRID_PGA]
        grid_ppk = parameters[self.GRID_PPK]
        grid_pgn = parameters[self.GRID_PGN]
        grid_phk = parameters[self.GRID_PHK]

        # Parameters BI
        pl = parameters[self.PL]
        ekoregion = parameters[self.EKOREGION]

        # Perhitungan BCPI
        # Join KPPK_XX, KPGN_XX, KPHK_XX ke GRID_PGA
        grid_bcpi1 = processing.run(
            "qgis:joinattributestable",
            {
                    'INPUT': grid_pga,
                    'FIELD': 'ID',
                    'INPUT_2': grid_ppk,
                    'FIELD_2': 'ID',
                    'FIELDS_TO_COPY': [f'PPK_{year}'],
                    'METHOD': 0,
                    'DISCARD_NONMATCHING': False,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        grid_bcpi2 = processing.run(
            "qgis:joinattributestable",
            {
                    'INPUT': grid_bcpi1,
                    'FIELD': 'ID',
                    'INPUT_2': grid_pgn,
                    'FIELD_2': 'ID',
                    'FIELDS_TO_COPY': [f'PGN_{year}'],
                    'METHOD': 0,
                    'DISCARD_NONMATCHING': False,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        grid_bcpi3 = processing.run(
            "qgis:joinattributestable",
            {
                    'INPUT': grid_bcpi2,
                    'FIELD': 'ID',
                    'INPUT_2': grid_phk,
                    'FIELD_2': 'ID',
                    'FIELDS_TO_COPY': [f'PHK_{year}_KK'],
                    'METHOD': 0,
                    'DISCARD_NONMATCHING': False,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # Hitung BCPI
        grid_bcpi = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': grid_bcpi3,
                'FIELD_NAME': 'BCPI',
                'FIELD_TYPE': 0,  # Decimal number (real)
                'FIELD_LENGTH': 10,
                'FIELD_PRECISION': 2,
                'NEW_FIELD': True,
                'FORMULA': f'( "PGA_{year}_KK" + "PPK_{year}" + "PGN_{year}" + "PHK_{year}_KK" ) / 4',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # Klasifikasi BCPI
        grid_bcpi_klas = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': grid_bcpi,
                'FIELD_NAME': 'KLS_BCPI',
                'FIELD_TYPE': 2,  # Text (string),
                'FIELD_LENGTH': 20,
                'NEW_FIELD': True,
                'FORMULA': '''
                CASE
                    WHEN "BCPI" <= 1.8 THEN 'Sangat Rendah'
                    WHEN "BCPI" > 1.8 AND "BCPI" <= 2.6 THEN 'Rendah'
                    WHEN "BCPI" > 2.6 AND "BCPI" <= 3.4 THEN 'Sedang'
                    WHEN "BCPI" > 3.4 AND "BCPI" <= 4.2 THEN 'Tinggi'
                    WHEN "BCPI" > 4.2 THEN 'Sangat Tinggi'
                    ELSE 0
                END
                ''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        grid_bcpi_klas = processing.run(
            "native:reprojectlayer", 
            {
                'INPUT':grid_bcpi_klas,
                'TARGET_CRS':QgsCoordinateReferenceSystem('EPSG:3395'),
                'CONVERT_CURVED_GEOMETRIES':False,
                'OPERATION':'+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +ellps=WGS84',
                'OUTPUT':'TEMPORARY_OUTPUT'
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        grid_bcpi_klas = processing.run(
            "native:fixgeometries", 
            {
                'INPUT': grid_bcpi_klas,
                'METHOD':1,
                'OUTPUT':'TEMPORARY_OUTPUT'
            }
        )["OUTPUT"]

        feedback.pushInfo('✅ Perhitungan BCPI selesai.')

        # HITUNG BI
        # Perhitungan IKG
        sebaran_karst_gambut = processing.run(
            "native:extractbyexpression",
            {
                'INPUT': ekoregion,
                'EXPRESSION': '''
                "KBA_250" IN (
                    'Dataran organik bermaterial gambut',
                    'Dataran solusional karst bermaterial batuan sedimen karbonat',
                    'Dataran solusional karst berombak-bergelombang bermaterial batuan sedimen karbonat',
                    'Pegunungan solusional karst bermaterial batuan sedimen karbonat',
                    'Perbukitan solusional karst bermaterial batuan sedimen karbonat'
                )''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # intersect sebaran karst dan gambut dengan PL
        intersect_karst_gambut = processing.run(
            "qgis:intersection",
            {
                'INPUT': sebaran_karst_gambut,
                'OVERLAY': pl,
                'INPUT_FIELDS': [],
                'OVERLAY_FIELDS': ['PL'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # Perhitungan indeks sebaran karst dan gambut (IKG)
        ikg = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': intersect_karst_gambut,
                'FIELD_NAME': 'KLS_KG',
                'FIELD_TYPE': 1,  # Whole number (integer)
                'NEW_FIELD': True,
                'FORMULA': '''
                    CASE
                        WHEN "PL" IN ('Permukiman', 'Permukiman Transmigrasi', 'Bandara/Pelabuhan', 'Tanah Terbuka', 'Pertambangan')
                            THEN 1
                        WHEN "PL" IN ('Pertanian Lahan Kering', 'Pertanian Lahan Kering Campur', 'Perkebunan', 'Sawah', 'Tambak')
                            THEN 2
                        WHEN "PL" IN ('Hutan Tanaman', 'Rawa', 'Semak Belukar', 'Semak Belukar Rawa')
                            THEN 3
                        WHEN "PL" IN ('Hutan Rawa Primer', 'Hutan Rawa Sekunder')
                            THEN 4
                        WHEN "PL" IN ('Hutan Lahan Kering Primer', 'Hutan Lahan Kering Sekunder', 'Hutan Mangrove Primer', 'Hutan Mangrove Sekunder', 'Savana/Padang Rumput', 'Tubuh Air')
                            THEN 5
                        ELSE 0
                    END
                ''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"] 

        ikg = processing.run(
            "native:reprojectlayer", 
            {
                'INPUT':ikg,
                'TARGET_CRS':QgsCoordinateReferenceSystem('EPSG:3395'),
                'CONVERT_CURVED_GEOMETRIES':False,
                'OPERATION':'+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +ellps=WGS84',
                'OUTPUT':'TEMPORARY_OUTPUT'
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        ikg = processing.run(
            "native:fixgeometries", 
            {
                'INPUT': ikg,
                'METHOD':1,
                'OUTPUT':'TEMPORARY_OUTPUT'
            }
        )["OUTPUT"]

        feedback.pushInfo('✅ Perhitungan Indeks Sebaran Karst dan Gambut selesai.')

        # 2b. Perhitungan Indikator Keragaman Habitat (Indikator Keragaman Tipe Habitat)
        habitat = self.parameterAsVectorLayer(parameters, self.HABITAT, context)

        habitat = processing.run(
            "native:reprojectlayer", 
            {
                'INPUT':habitat,
                'TARGET_CRS':QgsCoordinateReferenceSystem('EPSG:3395'),
                'CONVERT_CURVED_GEOMETRIES':False,
                'OPERATION':'+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +ellps=WGS84',
                'OUTPUT':'TEMPORARY_OUTPUT'
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        habitat = processing.run(
            "native:fixgeometries", 
            {
                'INPUT': habitat,
                'METHOD':1,
                'OUTPUT':'TEMPORARY_OUTPUT'
            }
        )["OUTPUT"]

        # ==== NOT USED BECAUSE CHANGE IN METHOD ===
        # Load data KK
        # plugin_root = os.path.dirname(__file__)
        # data_root = os.path.join(plugin_root, "data", f"jlh_phk")
        # data_root_kk = os.path.join(data_root, "KK")
        # kk_path = os.path.join(data_root_kk, "KK.gpkg")
        # kk = QgsVectorLayer(kk_path, "KK", "ogr")
        # habitat = parameters[self.HABITAT]
        # wilayah_ekoregion = parameters[self.WILAYAH_EKOREGION]
        
        # Here we use Zonal stat method because intersection takes a lot of time.
        #1. Gridding habitat raster from IUCN in 30" vector Grid using Zonal Stat
        # habitat = processing.run(
        #     "qgis:zonalstatisticsfb",
        #     {
        #         'INPUT': pl,
        #         'INPUT_RASTER': habitat,
        #         'RASTER_BAND': 1,
        #         'COLUMN_PREFIX': 'habitat_',
        #         'STATISTICS': [9], # majority
        #         'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        #     },
        #     context=context, feedback=feedback
        # )["OUTPUT"]

        # #3. Delete (extractbyattribute) habitat buatan (Habitat dengan PL Majority tertentu)
        # habitat_natural = processing.run(
        #     "native:extractbyexpression",
        #     {
        #         'INPUT': habitat,
        #         'EXPRESSION': '''
        #         "PL" NOT IN ('Bandara/Pelabuhan', 'Permukiman', 'Pertambangan', 'Tanah Terbuka', 'Permukiman Transmigrasi')
        #         ''',
        #         'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        #     },
        #     context=context, feedback=feedback
        # )["OUTPUT"]

        # #4. Intersect Vektor Habitat Natural dengan WE
        # habitat_we = processing.run(
        #     "qgis:intersection",
        #     {
        #         'INPUT': habitat_natural,
        #         'OVERLAY': wilayah_ekoregion,
        #         'INPUT_FIELDS': ['habitat_majority'],
        #         'OVERLAY_FIELDS': ['NAMA_WE'],
        #         'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        #     },
        #     context=context, feedback=feedback
        # )["OUTPUT"]

        # #4. Calculate for every WE (Wilayah Ekoregion) How Many unique habitat there
        # habitat_we_count = processing.run(
        #     "qgis:statisticsbycategories",
        #     {
        #         'INPUT': habitat_we,
        #         'CATEGORIES_FIELD_NAME': 'NAMA_WE',
        #         'VALUES_FIELD_NAME': 'habitat_majority',
        #         'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        #     },
        #     context=context, feedback=feedback
        # )["OUTPUT"]

        # #5. Join back count result to habitat_we_count
        # habitat_we_count_joined = processing.run(
        #     "qgis:joinattributestable",
        #     {
        #             'INPUT': wilayah_ekoregion,
        #             'FIELD': 'NAMA_WE',
        #             'INPUT_2': habitat_we_count,
        #             'FIELD_2': 'NAMA_WE',
        #             'FIELDS_TO_COPY': ['unique'],
        #             'METHOD': 0,
        #             'DISCARD_NONMATCHING': False,
        #             'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        #     },
        #     context=context, feedback=feedback
        # )["OUTPUT"]

        # #5. Calculate ISP based on how many species on every WE
        # isp = processing.run(
        #     "qgis:fieldcalculator",
        #     {
        #         'INPUT': habitat_we_count_joined,
        #         'FIELD_NAME': 'KLS_ISP',
        #         'FIELD_TYPE': 1,  # Decimal number (real)
        #         'NEW_FIELD': True,
        #         'FORMULA': '''
        #             CASE
        #                 WHEN "unique" <= 8 THEN 1
        #                 WHEN "unique" <= 12 THEN 2
        #                 WHEN "unique" <= 15 THEN 3
        #                 WHEN "unique" <= 19 THEN 4
        #                 WHEN "unique" >= 20 THEN 5
        #                 ELSE 0
        #             END
        #         ''',
        #         'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        #     },
        #     context=context, feedback=feedback
        # )["OUTPUT"]
         # ==== NOT USED BECAUSE CHANGE IN METHOD ===

        feedback.pushInfo('✅ Perhitungan Indeks Spesies Pemanfaatan selesai.')

        #2c. PERHITUNGAN RTE
        rte = self.parameterAsVectorLayer(parameters, self.RTE, context)
        rte = processing.run(
            "native:reprojectlayer", 
            {
                'INPUT':rte,
                'TARGET_CRS':QgsCoordinateReferenceSystem('EPSG:3395'),
                'CONVERT_CURVED_GEOMETRIES':False,
                'OPERATION':'+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +ellps=WGS84',
                'OUTPUT':'TEMPORARY_OUTPUT'
            },
            context=context, feedback=feedback
        )["OUTPUT"]
        
        rte = processing.run(
            "native:fixgeometries", 
            {
                'INPUT': rte,
                'METHOD':1,
                'OUTPUT':'TEMPORARY_OUTPUT'
            }
        )["OUTPUT"]
        
        # ==== NOT USED BECAUSE CHANGE IN METHOD ===
        # Intersect RTE dengan WE
        # rte_we = processing.run(
        #     "qgis:intersection",
        #     {
        #         'INPUT': rte,
        #         'OVERLAY': wilayah_ekoregion,
        #         'INPUT_FIELDS': ['SCI_NAME'],
        #         'OVERLAY_FIELDS': ['NAMA_WE'],
        #         'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        #     },
        #     context=context, feedback=feedback
        # )["OUTPUT"]

        # # Calculate RTE count per WE
        # rte_we_count = processing.run(
        #     "qgis:statisticsbycategories",
        #     {
        #         'INPUT': rte_we,
        #         'CATEGORIES_FIELD_NAME': 'NAMA_WE',
        #         'VALUES_FIELD_NAME': 'SCI_NAME',
        #         'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        #     },
        #     context=context, feedback=feedback
        # )["OUTPUT"]

        # # Join back RTE count to WE
        # rte_we_count_joined = processing.run(
        #     "qgis:joinattributestable",
        #     {
        #             'INPUT': isp,
        #             'FIELD': 'NAMA_WE',
        #             'INPUT_2': rte_we_count,
        #             'FIELD_2': 'NAMA_WE',
        #             'FIELDS_TO_COPY': ['count'],
        #             'METHOD': 0,
        #             'DISCARD_NONMATCHING': False,
        #             'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        #     },
        #     context=context, feedback=feedback
        # )["OUTPUT"]

        # # Calculate RTE score per WE
        # isp_rte = processing.run(
        #     "qgis:fieldcalculator",
        #     {
        #         'INPUT': rte_we_count_joined,
        #         'FIELD_NAME': 'JML_RTE',
        #         'FIELD_TYPE': 1,
        #         'NEW_FIELD': True,
        #         'FORMULA': '''
        #             CASE
        #                 WHEN "count" <= 29300 THEN 1
        #                 WHEN "count" > 29300 AND "count" <= 76000 THEN 2
        #                 WHEN "count" > 76000 AND "count" <= 148130 THEN 3   
        #                 WHEN "count" > 148130 AND "count" <= 285000 THEN 4
        #                 WHEN "count" > 285000 THEN 5
        #                 ELSE 0
        #             END
        #         ''',
        #         'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        #     },
        #     context=context, feedback=feedback
        # )["OUTPUT"]
         # ==== NOT USED BECAUSE CHANGE IN METHOD ===

        #2d. PERHITUNGAN INDEKS KONEKTIVITAS HUTAN
        # Ambil Feature PL = Hutan Lahan Kering Primer, Hutan Lahan Kering Sekunder, Hutan Mangrove Primer, Hutan Mangrove Sekunder, Hutan Rawa Primer, Hutan Rawa Sekunder, Hutan Tanaman
        hutan_raw = processing.run(
            "native:extractbyexpression",
            {
                'INPUT': pl,
                'EXPRESSION': '''
                "PL" IN (
                    'Hutan Lahan Kering Primer',
                    'Hutan Lahan Kering Sekunder',
                    'Hutan Mangrove Primer',
                    'Hutan Mangrove Sekunder',
                    'Hutan Rawa Primer',
                    'Hutan Rawa Sekunder',
                    'Hutan Tanaman'
                )''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # Multipart to singlepart hutan
        hutan_single = processing.run(
            "native:multiparttosingleparts",
            {
                'INPUT': hutan_raw,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # 2. Reproject dahulu ke EPSG:3395
        hutan_reproject = processing.run(
            "native:reprojectlayer",
            {
                'INPUT': hutan_single,
                'TARGET_CRS': 'EPSG:3395',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # # 3. Buffer Hutan 10 meter dengan dissolve namun tetap separate features
        hutan_buffer = processing.run(
            "native:buffer",
            {
                'INPUT': hutan_reproject,
                'DISTANCE': 100,
                'SEGMENTS': 5,
                'END_CAP_STYLE': 0,
                'JOIN_STYLE': 0,
                'MITER_LIMIT': 2,
                'DISSOLVE': True,
                'SEPARATE_DISJOINT': True,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # 4. Buat kolom identitas untuk setiap feature buffer hutan
        hutan_buffer_id = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': hutan_buffer,
                'FIELD_NAME': 'ID_BUF',
                'FIELD_TYPE': 1,  # Whole number (integer)
                'NEW_FIELD': True,
                'FORMULA': '@row_number',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # Dissolve hutan
        hutan_dissolve = processing.run(
            "native:dissolve",
            {
                'INPUT': hutan_reproject,
                'FIELD': [],
                'SEPARATE_DISJOINT': True,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # 5. Buat kolom luas area pada hutan asli
        hutan = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': hutan_dissolve,
                'FIELD_NAME': 'LUAS_HUTAN',
                'FIELD_TYPE': 0,  # Decimal number (real)
                'FIELD_PRECISION': 2,
                'NEW_FIELD': True,
                'FORMULA': '$area',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # 6. Buat kolom luas square pada hutan asli
        hutan = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': hutan,
                'FIELD_NAME': 'LUAS_SQ_HUTAN',
                'FIELD_TYPE': 0,  # Decimal number (real)
                'FIELD_PRECISION': 3,
                'NEW_FIELD': True,
                'FORMULA': '$area * $area',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # 5. Join by location antara hutan_buffer_id dengan hutan asli untuk mendapatkan luas hutan asli dalam setiap buffer
        hutan_buffer_join = processing.run(
            "qgis:joinattributesbylocation",
            {
                'INPUT': hutan,
                'JOIN': hutan_buffer_id,
                'PREDICATE': [0],  # intersects
                'JOIN_FIELDS': ['ID_BUF'],
                'METHOD': 0,  # Create separate feature for each matching feature (one-to
                'DISCARD_NONMATCHING': False,
                'PREFIX': '',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # 6. aggregate EMS (area total is sum of LUAS_HUTAN per ID_BUF)
        area_ems = processing.run(
            "native:aggregate",
            {
                'INPUT': hutan_buffer_join,
                'GROUP_BY': 'ID_BUF',
                'AGGREGATES': [
                    {
                        'aggregate': 'first_value',
                        'delimiter': ',',
                        'input': 'ID_BUF',
                        'length': 0,
                        'name': 'ID_BUF',
                        'type': 2
                    },
                    {
                        'aggregate': 'sum',
                        'delimiter': ',',
                        'input': 'LUAS_HUTAN',
                        'length': 0,
                        'name': 'SUM_AREA',
                        'precision': 2,
                        'type': 6
                    },
                    {
                        'aggregate': 'sum',
                        'delimiter': ',',
                        'input': 'LUAS_SQ_HUTAN',
                        'length': 0,
                        'name': 'SUM_SQ_AREA',
                        'precision': 2,
                        'type': 6
                    }
                ],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context,
            feedback=feedback
        )['OUTPUT']

        # 7. Field calculate EMS and Coherency
        ems_coherency = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': area_ems,
                'FIELD_NAME': 'EMS',
                'FIELD_TYPE': 0,  # Decimal number (real)
                'FIELD_PRECISION': 2,
                'NEW_FIELD': True,
                'FORMULA': '("SUM_SQ_AREA" / "SUM_AREA")',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        ems_final = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': ems_coherency,
                'FIELD_NAME': 'EMS_COH',
                'FIELD_TYPE': 0,  # Decimal number (real)
                'FIELD_PRECISION': 2,
                'NEW_FIELD': True,
                'FORMULA': '("EMS" / "SUM_AREA")*100',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # 12. Classify Konektivitas Hutan
        konektivitas_hutan = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': ems_final,
                'FIELD_NAME': 'KLS_KONEK',
                'FIELD_TYPE': 1,  # Text (string)
                'FIELD_LENGTH': 20,
                'NEW_FIELD': True,
                'FORMULA': '''
                    CASE
                        WHEN "EMS_COH" <= 20 THEN 1
                        WHEN "EMS_COH" > 20 AND "EMS_COH" <= 39 THEN 2
                        WHEN "EMS_COH" > 39 AND "EMS_COH" <= 59 THEN 3
                        WHEN "EMS_COH" > 59 AND "EMS_COH" <= 79 THEN 4
                        WHEN "EMS_COH" > 79 THEN 5
                        ELSE 0
                    END
                ''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        konektivitas_hutan = processing.run(
            "native:reprojectlayer", 
            {
                'INPUT':konektivitas_hutan,
                'TARGET_CRS':QgsCoordinateReferenceSystem('EPSG:3395'),
                'CONVERT_CURVED_GEOMETRIES':False,
                'OPERATION':'+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +ellps=WGS84',
                'OUTPUT':'TEMPORARY_OUTPUT'
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        konektivitas_hutan = processing.run(
            "native:fixgeometries", 
            {
                'INPUT': konektivitas_hutan,
                'METHOD':1,
                'OUTPUT':'TEMPORARY_OUTPUT'
            }
        )["OUTPUT"]

        feedback.pushInfo('✅ Perhitungan Indeks Konektivitas Hutan selesai.')

        # Menghitung BI
        # Intersect IKG, habitat, rte, dan konevektivitas hutan
        grid = self.parameterAsVectorLayer(parameters, self.GRID, context)
        union_bi_grid = processing.run(
            "qgis:union",
            {
                'INPUT': ikg,
                'OVERLAY': grid,
                'INPUT_FIELDS': ['KLS_KG'],
                'OVERLAY_FIELDS': [],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT,
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        union_bi_grid = processing.run(
            "native:deleteduplicategeometries", 
            {
             'INPUT':union_bi_grid,
             'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        union_habitat_grid = processing.run(
            "qgis:union",
            {
                'INPUT': habitat,
                'OVERLAY': grid,
                'INPUT_FIELDS': ['KLS_HAB'],
                'OVERLAY_FIELDS': [],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT,
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        union_habitat_grid = processing.run(
            "native:deleteduplicategeometries", 
            {
             'INPUT':union_habitat_grid,
             'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        intersect_bi = processing.run(
            "qgis:intersection",
            {
                'INPUT': union_bi_grid,
                'OVERLAY': union_habitat_grid,
                'INPUT_FIELDS': ['KLS_KG'],
                'OVERLAY_FIELDS': ['KLS_HAB'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT,
                'GRID_SIZE':0.1
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        union_konhutan_grid = processing.run(
            "qgis:union",
            {
                'INPUT': konektivitas_hutan,
                'OVERLAY': grid,
                'INPUT_FIELDS': ['KLS_HAB'],
                'OVERLAY_FIELDS': [],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT,
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        union_konhutan_grid = processing.run(
            "native:deleteduplicategeometries", 
            {
             'INPUT':union_habitat_grid,
             'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        intersect_bi2 = processing.run(
            "qgis:intersection",
            {
                'INPUT': intersect_bi,
                'OVERLAY': union_konhutan_grid,
                'INPUT_FIELDS': ['KLS_KG', 'KLS_HAB'],
                'OVERLAY_FIELDS': ['KLS_KONEK'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT,
                'GRID_SIZE':0.1
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        union_rte_grid = processing.run(
            "qgis:union",
            {
                'INPUT': rte,
                'OVERLAY': grid,
                'INPUT_FIELDS': ['KLS_RTE'],
                'OVERLAY_FIELDS': [],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT,
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        union_rte_grid = union_konhutan_grid = processing.run(
            "native:deleteduplicategeometries", 
            {
             'INPUT':union_rte_grid,
             'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        intersect_bi3 = processing.run(
            "qgis:intersection",
            {
                'INPUT': intersect_bi2,
                'OVERLAY': union_rte_grid,
                'INPUT_FIELDS': ['KLS_KG', 'KLS_HAB', 'KLS_KONEK'],
                'OVERLAY_FIELDS': ['KLS_RTE'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT,
                'GRID_SIZE':0.1
            },
            context=context, feedback=feedback
        )["OUTPUT"]
        
        # Fill all Null with 0
        intersect_bi3 = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': intersect_bi3,
                'FIELD_NAME': 'KLS_KG',
                'FIELD_TYPE': 1,  # Whole number (integer)
                'NEW_FIELD': False,
                'FORMULA': '''
                    CASE
                        WHEN "KLS_KG" IS NULL THEN 0
                        ELSE "KLS_KG"
                    END
                ''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        intersect_bi3 = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': intersect_bi3,
                'FIELD_NAME': 'KLS_HAB_KK',
                'FIELD_TYPE': 1,  # Whole number (integer)
                'NEW_FIELD': False,
                'FORMULA': '''
                    CASE
                        WHEN "KLS_HAB_KK" IS NULL THEN 0
                        ELSE "KLS_HAB_KK"
                    END
                ''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"] 

        intersect_bi3 = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': intersect_bi3,
                'FIELD_NAME': 'KLS_KONEK',
                'FIELD_TYPE': 1,  # Whole number (integer)
                'NEW_FIELD': False, 
                'FORMULA': '''
                    CASE
                        WHEN "KLS_KONEK" IS NULL THEN 0
                        ELSE "KLS_KONEK"
                    END
                ''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        intersect_bi3 = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': intersect_bi3,
                'FIELD_NAME': 'KLS_RTE',
                'FIELD_TYPE': 1,  # Whole number (integer)
                'NEW_FIELD': False, 
                'FORMULA': '''
                    CASE
                        WHEN "KLS_RTE" IS NULL THEN 0
                        ELSE "KLS_RTE"
                    END
                ''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # Hitung BI
        bi = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': intersect_bi3,
                'FIELD_NAME': 'BI',
                'FIELD_TYPE': 0,  # Decimal number (real)
                'FIELD_PRECISION': 2,
                'NEW_FIELD': True,
                'FORMULA': '''
                    ( "KLS_KG" + "KLS_RTE" + "KLS_HAB_KK" + "KLS_KONEK" ) / 4
                ''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # Menghitung kelas bi
        bi = processing.run(
            "native:fieldcalculator",
            {
                'INPUT': bi,
                'FIELD_NAME': "KLS_BI",
                'FIELD_TYPE': 1,
                'NEW_FIELD': True,
                'FORMULA': '''
                    CASE
                        WHEN "BI" <=1 THEN 1
                        WHEN "BI" > 1 AND "BI" <=2 THEN 2
                        WHEN "BI" > 2 AND "BI" <=3 THEN 3
                        WHEN "BI" > 3 AND "BI" <=4 THEN 4
                        WHEN "BI" > 4 THEN 5
                    END
                ''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        bi = processing.run(
            "qgis:refactorfields",
            {
                'INPUT': bi,  # your input layer (can be a QgsVectorLayer or file path)
                'FIELDS_MAPPING': [
                    {'name': 'PROVINSI', 'type': 10, 'expression': '"Provinsi"'},
                    {'name': 'KLS_KG', 'type': 6, 'expression': '"KLS_KG"'},
                    {'name': 'KLS_RTE', 'type': 6, 'expression': '"KLS_RTE"'},
                    {'name': 'KLS_HAB_KK', 'type': 6, 'expression': '"KLS_HAB_KK"'},
                    {'name': 'KLS_KONEK', 'type': 6, 'expression': '"KLS_KONEK"'},
                    {'name': 'BI', 'type': 6, 'expression': '"BI"'},
                    {'name': 'KLS_BI', 'type': 6, 'expression': '"KLS_BI"'}
                ],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        )["OUTPUT"]

        feedback.pushInfo('✅ Perhitungan BI selesai.')

        # Hitung IKP Kehati (Tidak Perlu Dirubah)
        # Gabungkan BCPI dan BI dengan union
        ikp_kehati = processing.run(
            "qgis:intersection",
            {
                'INPUT': grid_bcpi_klas,
                'OVERLAY': bi,
                'INPUT_FIELDS': [f'PPK_{year}', f'PGN_{year}', f'PGA_{year}_KK', f'PHK_{year}_KK','BCPI', 'KLS_BCPI'],
                'OVERLAY_FIELDS': [],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT,
                'GRID_SIZE':0.1
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        ikp_kehati = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': ikp_kehati,
                'FIELD_NAME': 'IKP',
                'FIELD_TYPE': 0,  # Decimal number (real)
                'FIELD_PRECISION': 2,
                'NEW_FIELD': True,
                'FORMULA': '( "BCPI" + "BI" ) / 2',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # Menghitung kelas ikp_kehati
        kls_ikp_kehati = processing.run(
            "native:fieldcalculator",
            {
                'INPUT': ikp_kehati,
                'FIELD_NAME': f"SKOR_IKP{year}",
                'FIELD_TYPE': 1,
                'NEW_FIELD': True,
                'FORMULA': '''
                    CASE
                        WHEN "IKP" <=1 THEN 1
                        WHEN "IKP" > 1 AND "IKP" <=2 THEN 2
                        WHEN "IKP" > 2 AND "IKP" <=3 THEN 3
                        WHEN "IKP" > 3 AND "IKP" <=4 THEN 4
                        WHEN "IKP" > 4 THEN 5
                    END
                ''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        
        grid_ikp_kehati = processing.run(
                "d3tlh:mcagrid",
                {
                    'GRID': grid,
                    'LAYER2': kls_ikp_kehati,
                    'LAYER2_FIELD' : f"SKOR_IKP{year}",
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                },
                context=context, feedback=feedback
        )["OUTPUT"]

        grid_ikp_kehati = processing.run(
            "native:deleteduplicategeometries", 
            {
             'INPUT':grid_ikp_kehati,
             'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
        )["OUTPUT"]

        feedback.pushInfo('✅ Perhitungan IKP Kehati selesai.')

        source = grid_ikp_kehati
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, source.fields(), source.wkbType(), source.sourceCrs())

        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break

            # Add a feature in the sink
            sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
            feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'ikpkehati'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('IKP Kehati')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'E. Indeks Kemampuan Pemanfaatan (IKP)'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
    
    def shortHelpString(self):
        return self.tr('''
Menghitung IKP Air per GRID.
Modul ini digunakan untuk menghitung indeks kemampuan pemanfaatan Air.

    ''')

    def createInstance(self):
        return IKPKehatiAlgorithm()
