# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OtomatisasiD3TLH
                                 A QGIS plugin
 Plugin yang membantu pengolahan D3TLH secara otomatis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-15
        copyright            : (C) 2025 by Yayasan Lokahita
        email                : fadillahazhardk@yayasanlokahita.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yayasan Lokahita'
__date__ = '2025-08-15'
__copyright__ = '(C) 2025 by Yayasan Lokahita'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSink,
)
import processing


class IKPLahanAlgorithm(QgsProcessingAlgorithm):
    # Parameters
    P_GRID_KPGN = 'P_GRID_KPGN'      # GRID JLH Pangan (kolom: ID, PULAU, KPGN_YY)
    P_PL = 'P_PL'                    # Penutup Lahan (PL)
    P_KWSHUTAN = 'P_KWSHUTAN'        # Kawasan Hutan (kwshutan)
    P_GRID_POP = 'P_GRID_POP'        # GRID Distribusi Penduduk (kolom: ID, POPGRIDYY)
    P_YEAR = 'P_YEAR'                # Tahun (e.g., 2024 → kolom suffix 24)
    P_JEP = 'P_JEP'                  # Jejak Ekologis Pangan (SJEPGN)
    P_JEB = 'P_JEB'                  # Jejak Ekologis Built-Up Land (SJEBUILT)

    # Output
    OUTPUT = 'OUTPUT'

    def tr(self, s):
        return QCoreApplication.translate('Processing', s)

    # Metadata
    def name(self):
        return 'ikplahan'

    def displayName(self):
        return self.tr('IKP Lahan')

    def groupId(self):
        return 'E. Indeks Kemampuan Pemanfaatan (IKP)'

    def group(self):
        return self.tr(self.groupId())

    def shortHelpString(self):
        return self.tr('''\
Modul ini digunakan untuk menghitung indeks kemampuan pemanfaatan lahan.
Berikut beberapa langkah dasar:
1. Siapkan data dasar: grid penyedia pangan, penutup lahan, kawasan hutan, dan distribusi penduduk.
2. Tentukan tahun & standar: Pilih tahun analisis (mis. 2024) serta nilai jejak ekologis pangan (SJEPGN) dan built-up land (SJEBUILT).
3. Tetapkan area yang boleh dimanfaatkan berdasarkan KPGN, jenis penutup lahan, dan status kawasan hutan, lalu kategorikan.
4. Ukur ketersediaan lahan per grid dalam satuan hektar.
5. Tambahkan data penduduk per grid.
6. Hitung kebutuhan (KEB_HA) dan indeks (IKPLHN).
7. Klasifikasikan IKPLHN: Sangat Rendah, Rendah, Sedang, Tinggi, Sangat Tinggi (dan Tidak Dihitung bila 0).''')

    def createInstance(self):
        return IKPLahanAlgorithm()

    def initAlgorithm(self, config=None):
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.P_GRID_KPGN,
                self.tr('GRID JLH Pangan (ID, PULAU, KPGN_YY)'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.P_PL,
                self.tr('Penutup Lahan (PL)'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.P_KWSHUTAN,
                self.tr('Kawasan Hutan (kwshutan)'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.P_GRID_POP,
                self.tr('GRID Distribusi Penduduk (ID, POPGRIDYY)'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.P_YEAR,
                self.tr('Tahun (Contoh: 2024)'),
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=2024
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.P_JEP,
                self.tr('Jejak Ekologis Pangan (SJEPGN)'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=0.08894
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.P_JEB,
                self.tr('Jejak Ekologis Built-Up Land (SJEBUILT)'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=0.0
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('IKP Lahan')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        # ---- Params
        grid_src = parameters[self.P_GRID_KPGN]
        pl_src = parameters[self.P_PL]
        kwsh_src = parameters[self.P_KWSHUTAN]
        grid_pop_src = parameters[self.P_GRID_POP]
        year = int(self.parameterAsDouble(parameters, self.P_YEAR, context))
        sjepgn = float(self.parameterAsDouble(parameters, self.P_JEP, context))
        sjebuilt = float(self.parameterAsDouble(parameters, self.P_JEB, context))

        yy = f"{year % 100:02d}"    # 2024 -> '24'
        fld_kpgn = f"KPGN_{yy}"
        fld_pop = f"POPGRID{yy}"

        # Simpan CRS awal GRID
        grid_src_layer = self.parameterAsSource(parameters, self.P_GRID_KPGN, context)
        crs_out = grid_src_layer.sourceCrs()

        # ===== Normalisasi CRS untuk overlay: PL & Kawasan -> CRS GRID
        pl_src = processing.run(
            'native:reprojectlayer',
            {'INPUT': pl_src, 'TARGET_CRS': crs_out, 'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']
        kwsh_src = processing.run(
            'native:reprojectlayer',
            {'INPUT': kwsh_src, 'TARGET_CRS': crs_out, 'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        # Index spasial
        processing.run('native:createspatialindex', {'INPUT': grid_src}, context=context, feedback=feedback)
        processing.run('native:createspatialindex', {'INPUT': pl_src},   context=context, feedback=feedback)
        processing.run('native:createspatialindex', {'INPUT': kwsh_src}, context=context, feedback=feedback)

        # Extent poligon GRID
        extent_poly = processing.run(
            'native:polygonfromlayerextent',
            {'INPUT': grid_src, 'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        # Subset tanpa memotong
        pl_sub = processing.run(
            'native:extractbylocation',
            {'INPUT': pl_src, 'PREDICATE': [0], 'INTERSECT': extent_poly, 'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']
        kwsh_sub = processing.run(
            'native:extractbylocation',
            {'INPUT': kwsh_src, 'PREDICATE': [0], 'INTERSECT': extent_poly, 'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        # Fix & filter Kawasan, dissolve, lalu fix lagi
        kwsh_fix = processing.run('native:fixgeometries',
                                  {'INPUT': kwsh_sub, 'OUTPUT': 'TEMPORARY_OUTPUT'},
                                  context=context, feedback=feedback)['OUTPUT']
        kwsh_nonkon = processing.run('native:extractbyexpression',
                                     {'INPUT': kwsh_fix,
                                      'EXPRESSION': "kwshutan <> 'Hutan Konservasi'",
                                      'OUTPUT': 'TEMPORARY_OUTPUT'},
                                     context=context, feedback=feedback)['OUTPUT']
        kwsh_nonkon_dis = processing.run('native:dissolve',
                                         {'INPUT': kwsh_nonkon, 'FIELD': ['kwshutan'],
                                          'OUTPUT': 'TEMPORARY_OUTPUT'},
                                         context=context, feedback=feedback)['OUTPUT']
        kwsh_nonkon_dis = processing.run('native:fixgeometries',
                                         {'INPUT': kwsh_nonkon_dis, 'OUTPUT': 'TEMPORARY_OUTPUT'},
                                         context=context, feedback=feedback)['OUTPUT']

        # Filter PL yang diperbolehkan, lalu fix
        pl_fix = processing.run('native:fixgeometries',
                                {'INPUT': pl_sub, 'OUTPUT': 'TEMPORARY_OUTPUT'},
                                context=context, feedback=feedback)['OUTPUT']
        pl_allowed = processing.run('native:extractbyexpression',
                                    {'INPUT': pl_fix,
                                     'EXPRESSION': "PL NOT IN ('Pertambangan','Bandara/ Pelabuhan','Permukiman','Transmigrasi','Lahan Terbuka')",
                                     'OUTPUT': 'TEMPORARY_OUTPUT'},
                                    context=context, feedback=feedback)['OUTPUT']
        pl_allowed = processing.run('native:fixgeometries',
                                    {'INPUT': pl_allowed, 'OUTPUT': 'TEMPORARY_OUTPUT'},
                                    context=context, feedback=feedback)['OUTPUT']

        # Intersect PL_allowed ∩ Kawasan_nonKonservasi (mask) dan fix
        mask = processing.run('native:intersection',
                              {'INPUT': pl_allowed, 'OVERLAY': kwsh_nonkon_dis,
                               'INPUT_FIELDS': [], 'OVERLAY_FIELDS': [],
                               'OVERLAY_FIELDS_PREFIX': '', 'OUTPUT': 'TEMPORARY_OUTPUT'},
                              context=context, feedback=feedback)['OUTPUT']
        mask = processing.run('native:fixgeometries',
                              {'INPUT': mask, 'OUTPUT': 'TEMPORARY_OUTPUT'},
                              context=context, feedback=feedback)['OUTPUT']

        # GRID yang beririsan mask → intersect satu kali
        grid_sub = processing.run('native:extractbylocation',
                                  {'INPUT': grid_src, 'PREDICATE': [0],
                                   'INTERSECT': mask, 'OUTPUT': 'TEMPORARY_OUTPUT'},
                                  context=context, feedback=feedback)['OUTPUT']
        inter = processing.run('native:intersection',
                               {'INPUT': grid_sub, 'OVERLAY': mask,
                                'INPUT_FIELDS': [], 'OVERLAY_FIELDS': [],
                                'OVERLAY_FIELDS_PREFIX': '', 'OUTPUT': 'TEMPORARY_OUTPUT'},
                               context=context, feedback=feedback)['OUTPUT']

        # Keep fields & REMARK per potongan
        kept = processing.run('native:retainfields',
                              {'INPUT': inter,
                               'FIELDS': ['ID', 'PULAU', 'PL', fld_kpgn, 'kwshutan'],
                               'OUTPUT': 'TEMPORARY_OUTPUT'},
                              context=context, feedback=feedback)['OUTPUT']

        expr_remark = (
            "CASE "
            f"WHEN (\"{fld_kpgn}\" IN ('Sedang','Tinggi','Sangat Tinggi') "
            "AND (PL NOT IN ('Pertambangan','Bandara/ Pelabuhan')) "
            "AND (kwshutan <> 'Hutan Konservasi')) "
            "THEN 'Ketersediaan Lahan Pangan dan Hunian' "
            f"WHEN (\"{fld_kpgn}\" IN ('Rendah','Sangat Rendah') "
            "AND (PL NOT IN ('Permukiman','Transmigrasi','Lahan Terbuka'))) "
            "THEN 'Ketersediaan Lahan Hunian' "
            "ELSE 'Lahan Tidak Dihitung' END"
        )
        ket = processing.run('native:fieldcalculator',
                             {'INPUT': kept, 'FIELD_NAME': 'REMARK',
                              'FIELD_TYPE': 2, 'FIELD_LENGTH': 255, 'FIELD_PRECISION': 0,
                              'NEW_FIELD': True, 'FORMULA': expr_remark,
                              'OUTPUT': 'TEMPORARY_OUTPUT'},
                             context=context, feedback=feedback)['OUTPUT']

        # Luas (ha) di EPSG:3395
        repro = processing.run('native:reprojectlayer',
                               {'INPUT': ket, 'TARGET_CRS': 'EPSG:3395',
                                'OUTPUT': 'TEMPORARY_OUTPUT'},
                               context=context, feedback=feedback)['OUTPUT']
        with_area = processing.run('native:fieldcalculator',
                                   {'INPUT': repro, 'FIELD_NAME': 'Luas_Ha',
                                    'FIELD_TYPE': 0, 'FIELD_LENGTH': 20, 'FIELD_PRECISION': 6,
                                    'NEW_FIELD': True, 'FORMULA': '$area / 10000',
                                    'OUTPUT': 'TEMPORARY_OUTPUT'},
                                   context=context, feedback=feedback)['OUTPUT']

        # Ringkas KET_HA
        filt = processing.run('native:extractbyexpression',
                              {'INPUT': with_area,
                               'EXPRESSION': "\"REMARK\" IN ('Ketersediaan Lahan Pangan dan Hunian','Ketersediaan Lahan Hunian')",
                               'OUTPUT': 'TEMPORARY_OUTPUT'},
                              context=context, feedback=feedback)['OUTPUT']
        stats = processing.run('qgis:statisticsbycategories',
                               {'INPUT': filt, 'CATEGORIES_FIELD_NAME': ['ID'],
                                'VALUES_FIELD_NAME': 'Luas_Ha', 'OUTPUT': 'TEMPORARY_OUTPUT'},
                               context=context, feedback=feedback)['OUTPUT']
        ket_tbl = processing.run('native:fieldcalculator',
                                 {'INPUT': stats, 'FIELD_NAME': 'KET_HA',
                                  'FIELD_TYPE': 0, 'FIELD_LENGTH': 20, 'FIELD_PRECISION': 6,
                                  'NEW_FIELD': True, 'FORMULA': 'coalesce("sum", 0)',
                                  'OUTPUT': 'TEMPORARY_OUTPUT'},
                                 context=context, feedback=feedback)['OUTPUT']
        ket_keep = processing.run('native:retainfields',
                                  {'INPUT': ket_tbl, 'FIELDS': ['ID', 'KET_HA'],
                                   'OUTPUT': 'TEMPORARY_OUTPUT'},
                                  context=context, feedback=feedback)['OUTPUT']

        # Ringkas per kategori → agar REMARK bisa dibawa ke level GRID
        # a) Pangan & Hunian
        filt_ph = processing.run('native:extractbyexpression',
                                 {'INPUT': with_area,
                                  'EXPRESSION': "\"REMARK\" = 'Ketersediaan Lahan Pangan dan Hunian'",
                                  'OUTPUT': 'TEMPORARY_OUTPUT'},
                                 context=context, feedback=feedback)['OUTPUT']
        stats_ph = processing.run('qgis:statisticsbycategories',
                                  {'INPUT': filt_ph, 'CATEGORIES_FIELD_NAME': ['ID'],
                                   'VALUES_FIELD_NAME': 'Luas_Ha', 'OUTPUT': 'TEMPORARY_OUTPUT'},
                                  context=context, feedback=feedback)['OUTPUT']
        ph_tbl = processing.run('native:fieldcalculator',
                                {'INPUT': stats_ph, 'FIELD_NAME': 'KET_PH_HA',
                                 'FIELD_TYPE': 0, 'FIELD_LENGTH': 20, 'FIELD_PRECISION': 6,
                                 'NEW_FIELD': True, 'FORMULA': 'coalesce("sum",0)',
                                 'OUTPUT': 'TEMPORARY_OUTPUT'},
                                context=context, feedback=feedback)['OUTPUT']
        ph_keep = processing.run('native:retainfields',
                                 {'INPUT': ph_tbl, 'FIELDS': ['ID', 'KET_PH_HA'],
                                  'OUTPUT': 'TEMPORARY_OUTPUT'},
                                 context=context, feedback=feedback)['OUTPUT']

        # b) Hunian
        filt_h = processing.run('native:extractbyexpression',
                                {'INPUT': with_area,
                                 'EXPRESSION': "\"REMARK\" = 'Ketersediaan Lahan Hunian'",
                                 'OUTPUT': 'TEMPORARY_OUTPUT'},
                                context=context, feedback=feedback)['OUTPUT']
        stats_h = processing.run('qgis:statisticsbycategories',
                                 {'INPUT': filt_h, 'CATEGORIES_FIELD_NAME': ['ID'],
                                  'VALUES_FIELD_NAME': 'Luas_Ha', 'OUTPUT': 'TEMPORARY_OUTPUT'},
                                 context=context, feedback=feedback)['OUTPUT']
        h_tbl = processing.run('native:fieldcalculator',
                               {'INPUT': stats_h, 'FIELD_NAME': 'KET_HUN_HA',
                                'FIELD_TYPE': 0, 'FIELD_LENGTH': 20, 'FIELD_PRECISION': 6,
                                'NEW_FIELD': True, 'FORMULA': 'coalesce("sum",0)',
                                'OUTPUT': 'TEMPORARY_OUTPUT'},
                               context=context, feedback=feedback)['OUTPUT']
        h_keep = processing.run('native:retainfields',
                                {'INPUT': h_tbl, 'FIELDS': ['ID', 'KET_HUN_HA'],
                                 'OUTPUT': 'TEMPORARY_OUTPUT'},
                                context=context, feedback=feedback)['OUTPUT']

        # Join KET_HA ke GRID
        joined1 = processing.run('native:joinattributestable',
                                 {'INPUT': grid_src, 'FIELD': 'ID',
                                  'INPUT_2': ket_keep, 'FIELD_2': 'ID',
                                  'FIELDS_TO_COPY': ['KET_HA'],
                                  'METHOD': 1, 'DISCARD_NONMATCHING': False, 'PREFIX': '',
                                  'OUTPUT': 'TEMPORARY_OUTPUT'},
                                 context=context, feedback=feedback)['OUTPUT']
        # Tambahkan per-kategori
        joined1b = processing.run('native:joinattributestable',
                                  {'INPUT': joined1, 'FIELD': 'ID',
                                   'INPUT_2': ph_keep, 'FIELD_2': 'ID',
                                   'FIELDS_TO_COPY': ['KET_PH_HA'],
                                   'METHOD': 1, 'DISCARD_NONMATCHING': False, 'PREFIX': '',
                                   'OUTPUT': 'TEMPORARY_OUTPUT'},
                                  context=context, feedback=feedback)['OUTPUT']
        joined1c = processing.run('native:joinattributestable',
                                  {'INPUT': joined1b, 'FIELD': 'ID',
                                   'INPUT_2': h_keep, 'FIELD_2': 'ID',
                                   'FIELDS_TO_COPY': ['KET_HUN_HA'],
                                   'METHOD': 1, 'DISCARD_NONMATCHING': False, 'PREFIX': '',
                                   'OUTPUT': 'TEMPORARY_OUTPUT'},
                                  context=context, feedback=feedback)['OUTPUT']

        # ====== PATCH JOIN POPGRID: normalisasi key (string) agar tidak NULL ======
        grid_with_key = processing.run(
            'native:fieldcalculator',
            {'INPUT': joined1c, 'FIELD_NAME': 'ID_KEY',
             'FIELD_TYPE': 2, 'FIELD_LENGTH': 64, 'FIELD_PRECISION': 0,
             'NEW_FIELD': True, 'FORMULA': 'trim(to_string("ID"))',
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        pop_with_key = processing.run(
            'native:fieldcalculator',
            {'INPUT': grid_pop_src, 'FIELD_NAME': 'ID_KEY',
             'FIELD_TYPE': 2, 'FIELD_LENGTH': 64, 'FIELD_PRECISION': 0,
             'NEW_FIELD': True, 'FORMULA': 'trim(to_string("ID"))',
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        # (opsional) index atribut untuk ngebut
        try:
            processing.run('native:createattributeindex',
                           {'INPUT': pop_with_key, 'FIELD': 'ID_KEY'},
                           context=context, feedback=feedback)
        except Exception:
            pass

        joined2 = processing.run(
            'native:joinattributestable',
            {'INPUT': grid_with_key, 'FIELD': 'ID_KEY',
             'INPUT_2': pop_with_key, 'FIELD_2': 'ID_KEY',
             'FIELDS_TO_COPY': [fld_pop],
             'METHOD': 1, 'DISCARD_NONMATCHING': False, 'PREFIX': '',
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        # Bentuk REMARK final di level GRID dari keberadaan kategori
        ket_final = processing.run(
            'native:fieldcalculator',
            {'INPUT': joined2, 'FIELD_NAME': 'REMARK',
             'FIELD_TYPE': 2, 'FIELD_LENGTH': 255, 'FIELD_PRECISION': 0,
             'NEW_FIELD': True,
             'FORMULA': (
                 "CASE "
                 "WHEN coalesce(\"KET_PH_HA\",0) > 0 AND coalesce(\"KET_HUN_HA\",0) = 0 "
                 "THEN 'Ketersediaan Lahan Pangan dan Hunian' "
                 "WHEN coalesce(\"KET_PH_HA\",0) = 0 AND coalesce(\"KET_HUN_HA\",0) > 0 "
                 "THEN 'Ketersediaan Lahan Hunian' "
                 "WHEN coalesce(\"KET_PH_HA\",0) > 0 AND coalesce(\"KET_HUN_HA\",0) > 0 "
                 "THEN 'Pangan & Hunian (Campuran)' "
                 "ELSE 'Lahan Tidak Dihitung' END"
             ),
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        base = processing.run(
            'native:retainfields',
            {'INPUT': ket_final,
             'FIELDS': ['ID', 'PULAU', fld_kpgn, 'KET_HA', fld_pop, 'REMARK'],
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        # ===== Turunan: SJEPGN, SJEBUILT, SJELHN, KEB_HA, AB_POP, IKPLHN, KIKPLHN =====
        step_sjepgn = processing.run(
            'native:fieldcalculator',
            {'INPUT': base, 'FIELD_NAME': 'SJEPGN',
             'FIELD_TYPE': 0, 'FIELD_LENGTH': 20, 'FIELD_PRECISION': 6,
             'NEW_FIELD': True, 'FORMULA': f'{sjepgn}',
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        step_sjebuilt = processing.run(
            'native:fieldcalculator',
            {'INPUT': step_sjepgn, 'FIELD_NAME': 'SJEBUILT',
             'FIELD_TYPE': 0, 'FIELD_LENGTH': 20, 'FIELD_PRECISION': 6,
             'NEW_FIELD': True, 'FORMULA': f'{sjebuilt}',
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        step_sjelhn = processing.run(
            'native:fieldcalculator',
            {'INPUT': step_sjebuilt, 'FIELD_NAME': 'SJELHN',
             'FIELD_TYPE': 0, 'FIELD_LENGTH': 20, 'FIELD_PRECISION': 6,
             'NEW_FIELD': True, 'FORMULA': 'coalesce("SJEPGN",0) + coalesce("SJEBUILT",0)',
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        # KEB_HA dengan aturan REMARK & POPGRID
        # - Jika REMARK Pangan/Hunian & POP=0 => KEB_HA = SJELHN
        # - REMARK selain itu => KEB_HA = SJELHN * POPGRID
        step_keb = processing.run(
            'native:fieldcalculator',
            {'INPUT': step_sjelhn, 'FIELD_NAME': 'KEB_HA',
             'FIELD_TYPE': 0, 'FIELD_LENGTH': 20, 'FIELD_PRECISION': 6,
             'NEW_FIELD': True,
             'FORMULA': (
                 f"CASE "
                 f"WHEN \"REMARK\" IN ('Ketersediaan Lahan Pangan dan Hunian','Ketersediaan Lahan Hunian') "
                 f"THEN CASE WHEN coalesce(\"{fld_pop}\",0)=0 "
                 f"          THEN coalesce(\"SJELHN\",0) "
                 f"          ELSE coalesce(\"SJELHN\",0)*coalesce(\"{fld_pop}\",0) END "
                 f"ELSE coalesce(\"SJELHN\",0)*coalesce(\"{fld_pop}\",0) "
                 f"END"
             ),
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        # AB_POP = KET_HA / SJELHN (integer)
        step_ab = processing.run(
            'native:fieldcalculator',
            {'INPUT': step_keb, 'FIELD_NAME': 'AB_POP',
             'FIELD_TYPE': 1, 'FIELD_LENGTH': 10, 'FIELD_PRECISION': 0,
             'NEW_FIELD': True,
             'FORMULA': 'to_int( case when coalesce("SJELHN",0)=0 '
                        'then 0 else coalesce("KET_HA",0)/nullif("SJELHN",0) end )',
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        # IKPLHN = KET_HA / KEB_HA
        step_ikp = processing.run(
            'native:fieldcalculator',
            {'INPUT': step_ab, 'FIELD_NAME': 'IKPLHN',
             'FIELD_TYPE': 0, 'FIELD_LENGTH': 20, 'FIELD_PRECISION': 6,
             'NEW_FIELD': True,
             'FORMULA': 'case when coalesce("KEB_HA",0)=0 '
                        'then 0 else coalesce("KET_HA",0)/nullif("KEB_HA",0) end',
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        expr_kik = (
            "CASE WHEN \"IKPLHN\" = 0 THEN 'Tidak Dihitung' "
            "WHEN (\"IKPLHN\" > 0 AND \"IKPLHN\" <= 0.05) THEN 'Sangat Rendah' "
            "WHEN (\"IKPLHN\" > 0.05 AND \"IKPLHN\" <= 1.0) THEN 'Rendah' "
            "WHEN (\"IKPLHN\" > 1.0 AND \"IKPLHN\" <= 1.5) THEN 'Sedang' "
            "WHEN (\"IKPLHN\" > 1.5 AND \"IKPLHN\" <= 2) THEN 'Tinggi' "
            "WHEN (\"IKPLHN\" > 2) THEN 'Sangat Tinggi' "
            "ELSE 'Tidak Dihitung' END"
        )
        final_tmp = processing.run(
            'native:fieldcalculator',
            {'INPUT': step_ikp, 'FIELD_NAME': 'KIKPLHN',
             'FIELD_TYPE': 2, 'FIELD_LENGTH': 255, 'FIELD_PRECISION': 0,
             'NEW_FIELD': True, 'FORMULA': expr_kik,
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        # Kembalikan ke CRS awal & tulis sink
        final = processing.run('native:reprojectlayer',
                               {'INPUT': final_tmp, 'TARGET_CRS': crs_out,
                                'OUTPUT': 'TEMPORARY_OUTPUT'},
                               context=context, feedback=feedback)['OUTPUT']

        # Susun urutan kolom utama
        final_sel = processing.run(
            'native:retainfields',
            {'INPUT': final,
             'FIELDS': ['ID', 'PULAU', fld_kpgn, 'KET_HA', fld_pop, 'REMARK',
                        'SJEPGN', 'SJEBUILT', 'SJELHN', 'KEB_HA', 'AB_POP',
                        'IKPLHN', 'KIKPLHN'],
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback
        )['OUTPUT']

        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context,
            final_sel.fields(), final_sel.wkbType(), final_sel.sourceCrs()
        )
        for f in final_sel.getFeatures():
            sink.addFeature(f)

        return {self.OUTPUT: dest_id}
