# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OtomatisasiD3TLH
                                 A QGIS plugin
 Plugin yang membantu pengolahan D3TLH secara otomatis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-15
        copyright            : (C) 2025 by Yayasan Lokahita
        email                : fadillahazhardk@yayasanlokahita.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yayasan Lokahita'
__date__ = '2025-08-15'
__copyright__ = '(C) 2025 by Yayasan Lokahita'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterRasterLayer,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSink,
    QgsRasterBandStats,
    QgsVectorLayer,
    QgsRasterLayer,
    QgsProject,
    QgsProcessingParameterVectorLayer
)
import processing

class IKPUdaraAlgorithm(QgsProcessingAlgorithm):
    # Parameters
    GRID_KPKU = 'GRID_KPKU'
    PM25 = 'PM25'
    IPS = 'IPS' # Indeks Proyeksi Suhu

    # Output
    OUTPUT = 'OUTPUT'

    # Constant
    bakumutu_pm25 = 15 #15µg/m^3 sesuai standar PP22/2021
    
    def initAlgorithm(self, config=None):
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.GRID_KPKU,
                self.tr('Grid JLH Udara'),
                [QgsProcessing.TypeVectorAnyGeometry],
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.IPS,
                self.tr('Indeks Proyeksi Suhu'),
                [QgsProcessing.TypeVectorAnyGeometry],
            )
        )

        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.PM25,
                self.tr('Raster PM25 (Time Averaged) kg m-3')
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('IKP Udara')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        # Parameters
        grid_src = parameters[self.GRID_KPKU]
        pm25_raster = self.parameterAsRasterLayer(parameters, self.PM25, context)
        ips = parameters[self.IPS]

        # Standarize PM25 raster
        # 1. Reclassify to Equal Interval
        # Get raster statistics
        provider = pm25_raster.dataProvider()
        stats = provider.bandStatistics(1, QgsRasterBandStats.All, pm25_raster.extent(), 0)

        min_val = stats.minimumValue
        max_val = stats.maximumValue

        # Define number of classes
        n_classes = 11
        interval = (max_val - min_val) / n_classes

        # Build reclass table: [low, high, new_value]
        reclass_table = []
        mid_table = []
        for i in range(n_classes):
            low = min_val + i * interval
            high = min_val + (i + 1) * interval
            new_value = i + 1
            mid_value = ((low + high) / 2) * 1000000000
            reclass_table.extend([low, high, new_value])
            mid_table.append({f'{new_value}': mid_value})

        # Run reclassify by table
        reclass_pm25 = processing.run(
            "qgis:reclassifybytable",
            {
                "INPUT_RASTER": parameters[self.PM25],
                "RASTER_BAND": 1,
                "TABLE": reclass_table,
                "NO_DATA": -9999,
                "RANGE_BOUNDARIES": 0,  # 0 = min < x ≤ max
                "NODATA_FOR_MISSING": True,
                "DATA_TYPE": 5,  # Float32
                "OUTPUT": QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback.pushInfo("Finish Reclassify PM2.5 Raster Data")
        )["OUTPUT"]

        reclass_pm25 = QgsRasterLayer(reclass_pm25, 'reclass_pm25')

        # 2. Polygonize the result
        polygonize_pm25 = processing.run(
            "gdal:polygonize",
            {
                'INPUT': reclass_pm25,
                'BAND': 1,
                'FIELD': 'gridcode',
                'EIGHT_CONNECTEDNESS': False,
                'EXTRA': '',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback.pushInfo("Finish Polygonize Reclassified PM2.5")
        )["OUTPUT"]

        polygonize_pm25 = QgsVectorLayer(polygonize_pm25, 'konsentrasi_pm25', "ogr")

        # 3. Input mid value based on gridcode
        case_when_expr = "CASE\n"
        for item in mid_table:
            for key, val in item.items():
                case_when_expr += f'    WHEN "gridcode" = {key} THEN {val}\n'
        case_when_expr += "END"
        mid_pm25 = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': polygonize_pm25,
                'FIELD_NAME': 'NT_PM25',
                'FIELD_TYPE': 0,
                'FIELD_LENGTH': 20,
                'FIELD_PRECISION': 10,
                'NEW_FIELD': True,
                'FORMULA': case_when_expr,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback.pushInfo("Get Median Value for Every Class in PM2.5 Raster")
        )["OUTPUT"]

        # 3. Menghitung IP (Konsentrasi PM2.5 / Baku mutu PM2.5)
        ip_pm25 = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': mid_pm25,
                'FIELD_NAME': 'IPM25',
                'FIELD_TYPE': 0,
                'FIELD_LENGTH': 20,
                'FIELD_PRECISION': 10,
                'NEW_FIELD': True,
                'FORMULA': f'"NT_PM25"/{self.bakumutu_pm25}',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback.pushInfo("Selesai Menghitung IP untuk PM2.5")
        )["OUTPUT"]

        # 4. Menghitung Indeks PM 2.5
        indeks_pm25 = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': ip_pm25,
                'FIELD_NAME': 'IKU_PM25',
                'FIELD_TYPE': 0,
                'FIELD_LENGTH': 20,
                'FIELD_PRECISION': 3,
                'NEW_FIELD': True,
                'FORMULA': '100-((50/0.9) * ("IPM25" - 0.1))',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback.pushInfo("Selesai menghitung IKU_PM2.5")
        )["OUTPUT"]

        idw_indeks_pm25 = processing.run(
            "gdal:gridinversedistance",
            {
                'INPUT': indeks_pm25,
                'Z_FIELD': 'IKU_PM25',       # Field to interpolate
                'POWER': 2.0,                # IDW power parameter (p)
                'SMOOTHING': 0.0,            # Optional smoothing factor
                'RADIUS_1': 0.0,             # Search radius X (0 = auto)
                'RADIUS_2': 0.0,             # Search radius Y (0 = auto)
                'ANGLE': 0.0,                # Angle for anisotropy (deg)
                'MIN_POINTS': 0,             # Minimum points to use
                'MAX_POINTS': 0,             # 0 = unlimited
                'NODATA': None,             # NoData value
                'OPTIONS': '',               # Additional GDAL options
                'DATA_TYPE': 5,              # Float32
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT,        # Output GeoTIFF
                'OUTPUT_EXTENT': None,       # Optional custom extent
                'OUTPUT_SIZE': 1000,         # Raster width/height in pixels
            }
        )["OUTPUT"]

        feedback.pushInfo("Selesai Interpolasi IKU_PM2.5")

        # Zonal Stat
        zon_stat_indeks_pm25 = processing.run(
            "qgis:zonalstatisticsfb",
            {
                'INPUT': grid_src,
                'INPUT_RASTER' : idw_indeks_pm25,
                'RASTER_BAND': 1,
                'COLUMN_PREFIX': 'idw_',
                'STATISTICS': [2],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        zon_stat_indeks_pm25_renamed = processing.run(
            "qgis:renametablefield",
            {
                'INPUT': zon_stat_indeks_pm25,
                'FIELD': 'idw_mean',
                'NEW_NAME': 'IKU_PM25',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # 5. Kategorisasi Indeks PM2.5
        kategori_pm25 = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': zon_stat_indeks_pm25_renamed,
                'FIELD_NAME': 'IKU',
                'FIELD_TYPE': 1,
                'NEW_FIELD': True,
                'FORMULA': '''
                    CASE
                        WHEN "IKU_PM25" >= 90 THEN 5
                        WHEN "IKU_PM25" >= 70 AND "IKU_PM25" < 90 THEN 4
                        WHEN "IKU_PM25" >= 50 AND "IKU_PM25" < 70 THEN 3
                        WHEN "IKU_PM25" >= 25 AND "IKU_PM25" < 50 THEN 2
                        WHEN "IKU_PM25" < 25 THEN 1
                    END
                ''',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # Intersect Grid, IPS, dan IKU PM2.5
        intersect_pm25_ips = processing.run(
            "qgis:intersection",
            {
                'INPUT': kategori_pm25,
                'OVERLAY': ips,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        intersect_seluruh = processing.run(
            "qgis:intersection",
            {
                'INPUT': intersect_pm25_ips,
                'OVERLAY': grid_src,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback.pushInfo("Finish Intersect Grid, IPS, dan IKU PM2.5")
        )["OUTPUT"]

        # Menghitung IKP Udara per Polygon
        IKP_udara_poly = processing.run(
            "qgis:fieldcalculator",
            {
                'INPUT': intersect_seluruh,
                'FIELD_NAME': 'IKP_Udara',
                'FIELD_TYPE': 0,
                'FIELD_LENGTH': 20,
                'FIELD_PRECISION': 3,
                'NEW_FIELD': True,
                'FORMULA': f'("KPKU_24"+"NORM_HEAT"+IKU_PM25)/3',
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            },
            context=context, feedback=feedback
        )["OUTPUT"]

        # Menghitung IKP Udara per Grid
        IKP_udara_poly_summed = processing.run(
                "qgis:statisticsbycategories",
                {
                    'INPUT': IKP_udara_poly,
                    'CATEGORIES_FIELD_NAME': ['ID'],
                    'VALUES_FIELD_NAME': 'IKP_Udara',
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                },
                context=context, feedback=feedback
        )["OUTPUT"]

        IKP_udara_joined = processing.run(
                "qgis:joinattributestable",
                {
                    'INPUT': grid_src,
                    'FIELD': 'ID',
                    'INPUT_2': IKP_udara_poly_summed,
                    'FIELD_2': 'ID',
                    'FIELDS_TO_COPY': ['sum'],
                    'METHOD': 0,
                    'DISCARD_NONMATCHING': False,
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                },
                context=context, feedback=feedback
        )["OUTPUT"]

        IKP_udara_grid = processing.run(
                "qgis:renametablefield",
                {
                    'INPUT': IKP_udara_joined,
                    'FIELD': 'sum',
                    'NEW_NAME': 'IKP_Udara',
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                },
                context=context, feedback=feedback
        )["OUTPUT"]

        
        final = IKP_udara_grid

        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context,
            final.fields(), final.wkbType(), final.sourceCrs()
        )

        for f in final.getFeatures():
            sink.addFeature(f)

        return {self.OUTPUT: dest_id}

    def tr(self, s):
        return QCoreApplication.translate('Processing', s)

    # Metadata
    def name(self):
        return 'ikp_udara'
    
    def displayName(self):
        return self.tr('IKP Udara')
    
    def groupId(self):
        return '04. Indeks Kemampuan Pemanfaatan (IKP)'
    
    def group(self):
        return self.tr(self.groupId())
    
    def shortHelpString(self):
        return self.tr('''
Menghitung IKP Lahan per GRID.
Modul ini digunakan untuk menghitung indeks kemampuan pemanfaatan udara.

    ''')

    def createInstance(self):
        return IKPUdaraAlgorithm()

