# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OtomatisasiD3TLH
                                 A QGIS plugin
 Plugin yang membantu pengolahan D3TLH secara otomatis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-15
        copyright            : (C) 2025 by Yayasan Lokahita
        email                : fadillahazhardk@yayasanlokahita.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = "Yayasan Lokahita"
__date__ = "2025-08-15"
__copyright__ = "(C) 2025 by Yayasan Lokahita"

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = "$Format:%H$"

from qgis.PyQt.QtCore import QCoreApplication, Qt
from qgis.PyQt.QtGui import QColor
from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingParameterVectorLayer,
    QgsProcessingParameterEnum,
    QgsProcessingParameterString,
    QgsProcessingParameterNumber,
    QgsCategorizedSymbolRenderer,
    QgsRendererCategory,
    QgsSymbol,
    QgsProcessingException,
)
import re


class ApplyStandardStylesAlgorithm(QgsProcessingAlgorithm):
    P_LAYER = "LAYER"
    P_THEME = "THEME"
    P_YEAR = "YEAR"
    P_FIELD = "FIELD"

    THEMES = [
        "JLH Pendukung Habitat & Kehati (Nasional) — KPHK_YY_KK",
        "JLH Pendukung Habitat & Kehati (Kab/Kota) — KPHK_YY_KK",
        "JLH Pengaturan Kualitas Udara (Nasional) — KPKU_YY",
        "JLH Pengaturan Kualitas Udara (Kab/Kota) — KPKU_YY_KK",
        "JLH Pengaturan Air (Nasional) — KPGA_YY_KK",
        "JLH Pengaturan Air (Kab/Kota) — KPGA_YY_KK",
        "JLH Penyedia Air (Nasional) — KPYA_YY",
        "JLH Penyedia Air (Kab/Kota) — KPYA_YY_KK",
        "JLH Penyedia Pangan (Nasional/Kab/Kota) — KPGN_YY",
        "JLH Penyerapan & Penyimpanan Karbon (Nasional/Kab/Kota) — KPPK_YY",
        "IKP Air — KIKPAIR",
        "IKP Kehati — KIKPLH",
        "IKP Lahan — KIKPLHN",
        "IKP Udara — KIKPUDR",
    ]
    (
        THEME_JLH_KPHK_N,
        THEME_JLH_KPHK_KK,
        THEME_JLH_KPKU_N,
        THEME_JLH_KPKU_KK,
        THEME_JLH_KPGA_N,
        THEME_JLH_KPGA_KK,
        THEME_JLH_KPYA_N,
        THEME_JLH_KPYA_KK,
        THEME_JLH_KPGN,
        THEME_JLH_KPPK,
        THEME_IKP_AIR,
        THEME_IKP_KEHATI,
        THEME_IKP_LAHAN,
        THEME_IKP_UDARA,
    ) = range(14)

    # -------------------- metadata --------------------
    def tr(self, s):
        return QCoreApplication.translate("Processing", s)

    def name(self):
        return "simbologi_jlh_ikp_standar"

    def displayName(self):
        return self.tr("Map symbology")

    def groupId(self):
        return "G. Styling"

    def group(self):
        return self.tr(self.groupId())

    def shortHelpString(self):
        return self.tr(
            """\
🇮🇩 ID  Modul ini menerapkan simbologi standar secara in-place (langsung pada layer terpilih) untuk JLH dan IKP. Kategori yang digunakan: Sangat Rendah, Rendah, Sedang, Tinggi, Sangat Tinggi (khusus IKP Lahan juga Tidak Dihitung).

Alur pakai:
1) Pilih Layer target.
2) Pilih Tema (JLH/IKP) sesuai field pada data.
3) (Opsional) Isi Tahun: untuk tema JLH membentuk nama kolom seperti "..._YY" (mis. 2024 → "..._24").
4) (Opsional) Isi Nama kolom kategori bila ingin menimpa deteksi otomatis.
5) Klik Run dan simbologi kategori diterapkan ke layer yang sama (tidak membuat layer baru).

──────────────

🌍 EN  This module applies standard symbology in-place to the selected layer for JLH dan IKP. Categories used: Very Low, Low, Medium, High, Very High (IKP Land also Not Computed).

Usage:
1) Select the Layer.
2) Choose the Theme (JLH/IKP) matching your data field.
3) (Optional) Set Year → for JLH themes, builds field names like "..._YY" (e.g., 2024 → "..._24").
4) (Optional) Provide Category field name to override auto-detection.
5) Click Run → a categorized renderer is applied to the same layer (no new layer is created)."""
        )

    def createInstance(self):
        return ApplyStandardStylesAlgorithm()

    # -------------------- params ----------------------
    def initAlgorithm(self, config=None):
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.P_LAYER, self.tr("Layer"), [QgsProcessing.TypeVectorAnyGeometry]
            )
        )
        self.addParameter(
            QgsProcessingParameterEnum(
                self.P_THEME,
                self.tr("Tema"),
                options=self.THEMES,
                defaultValue=self.THEME_JLH_KPGN,
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.P_YEAR,
                self.tr("Tahun (mis. 2024 → YY=24)"),
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=2024,
                optional=True,
            )
        )
        self.addParameter(
            QgsProcessingParameterString(
                self.P_FIELD,
                self.tr("Nama kolom kategori (kosongkan untuk autodetect)"),
                defaultValue="",
                optional=True,
            )
        )

    # -------------------- helpers ---------------------
    def _no_outline(self, sym: QgsSymbol):
        for sl in sym.symbolLayers():
            if hasattr(sl, "setStrokeStyle"):
                sl.setStrokeStyle(Qt.NoPen)
            if hasattr(sl, "setStrokeColor"):
                sl.setStrokeColor(QColor(0, 0, 0, 0))
            if hasattr(sl, "setStrokeWidth"):
                sl.setStrokeWidth(0)
            if hasattr(sl, "setOutlineStyle"):
                sl.setOutlineStyle(Qt.NoPen)
            if hasattr(sl, "setOutlineColor"):
                sl.setOutlineColor(QColor(0, 0, 0, 0))
            if hasattr(sl, "setOutlineWidth"):
                sl.setOutlineWidth(0)

    def _cat(self, layer, label, r, g, b):
        base = QgsSymbol.defaultSymbol(layer.geometryType())
        sym = base.clone()
        sym.setColor(QColor(r, g, b))
        self._no_outline(sym)
        return QgsRendererCategory(label, sym, label)

    # Palet JLH (RdYlGn)
    def _palette_jlh(self, layer):
        return [
            self._cat(layer, "Sangat Rendah", 215, 25, 28),  # #D7191C
            self._cat(layer, "Rendah", 253, 174, 97),  # #FDAE61
            self._cat(layer, "Sedang", 255, 255, 192),  # #FFFFC0
            self._cat(layer, "Tinggi", 166, 217, 106),  # #A6D96A
            self._cat(layer, "Sangat Tinggi", 26, 150, 65),  # #1A9641
        ]

    # IKP Air (biru)
    def _palette_ikp_air(self, layer):
        return [
            self._cat(layer, "Sangat Rendah", 150, 200, 255),
            self._cat(layer, "Rendah", 100, 180, 240),
            self._cat(layer, "Sedang", 50, 160, 230),
            self._cat(layer, "Tinggi", 20, 120, 220),
            self._cat(layer, "Sangat Tinggi", 0, 70, 180),
        ]

    # IKP Kehati (hijau → kuning; urutan sesuai permintaan)
    def _palette_ikp_kehati(self, layer):
        return [
            self._cat(layer, "Sangat Tinggi", 0, 100, 0),  # Dark Green
            self._cat(layer, "Tinggi", 85, 150, 0),  # Medium Green
            self._cat(layer, "Sedang", 170, 200, 0),  # Yellow-Green
            self._cat(layer, "Rendah", 220, 220, 0),  # Golden Yellow
            self._cat(layer, "Sangat Rendah", 255, 255, 0),  # Bright Yellow
        ]

    # IKP Lahan (oranye-coklat) + Tidak Dihitung (abu-abu)
    def _palette_ikp_lahan(self, layer):
        cats = [
            self._cat(layer, "Sangat Rendah", 255, 230, 200),  # #FFE6C8
            self._cat(layer, "Rendah", 255, 190, 120),  # #FFBE78
            self._cat(layer, "Sedang", 230, 135, 60),  # #E6873C
            self._cat(layer, "Tinggi", 180, 95, 30),  # #B45F1E
            self._cat(layer, "Sangat Tinggi", 120, 60, 20),  # #783C14
        ]
        # Tambah kategori "Tidak Dihitung"
        base = QgsSymbol.defaultSymbol(layer.geometryType())
        sym = base.clone()
        sym.setColor(QColor(222, 222, 222))  # ~RGB(239.27,239.27,239.27)
        self._no_outline(sym)
        cats.append(QgsRendererCategory("Tidak Dihitung", sym, "Tidak Dihitung"))
        return cats

    # IKP Udara (grays-blue)
    def _palette_ikp_udara(self, layer):
        return [
            self._cat(layer, "Sangat Rendah", 240, 245, 245),  # #F0F5F5
            self._cat(layer, "Rendah", 210, 220, 225),  # #D2DCE1
            self._cat(layer, "Sedang", 170, 180, 190),  # #AAB4BE
            self._cat(layer, "Tinggi", 120, 130, 145),  # #788291
            self._cat(layer, "Sangat Tinggi", 80, 90, 105),  # #505A69
        ]

    # Template field per tema (pakai YY)
    def _field_template(self, theme_index):
        return {
            self.THEME_JLH_KPHK_N: "KPHK_YY_KK",
            self.THEME_JLH_KPHK_KK: "KPHK_YY_KK",
            self.THEME_JLH_KPKU_N: "KPKU_YY",
            self.THEME_JLH_KPKU_KK: "KPKU_YY_KK",
            self.THEME_JLH_KPGA_N: "KPGA_YY_KK",
            self.THEME_JLH_KPGA_KK: "KPGA_YY_KK",
            self.THEME_JLH_KPYA_N: "KPYA_YY",
            self.THEME_JLH_KPYA_KK: "KPYA_YY_KK",
            self.THEME_JLH_KPGN: "KPGN_YY",
            self.THEME_JLH_KPPK: "KPPK_YY",
            self.THEME_IKP_AIR: "KIKPAIR",
            self.THEME_IKP_KEHATI: "KIKPLH",
            self.THEME_IKP_LAHAN: "KIKPLHN",
            self.THEME_IKP_UDARA: "KIKPUDR",
        }[theme_index]

    def _autodetect_field(self, layer, theme_index, year_opt):
        names = [f.name() for f in layer.fields()]
        templ = self._field_template(theme_index)

        # IKP themes: langsung pakai nama field
        if "KIKP" in templ or templ in ("KIKPLH", "KIKPLHN"):
            if templ not in names:
                raise QgsProcessingException(self.tr(f"Kolom {templ} tidak ditemukan."))
            return templ

        # JLH themes: punya placeholder YY
        if "YY" in templ:
            if year_opt is not None:
                yy = f"{int(year_opt) % 100:02d}"
                candidate = templ.replace("YY", yy)
                if candidate in names:
                    return candidate

            # fallback: cari pola yang sama dengan regex
            base = templ.replace("YY", r"(\d{2})")
            pattern = re.compile("^" + base + "$")
            candidates = [n for n in names if pattern.fullmatch(n)]
            if candidates:
                # ambil yang suffix YY paling besar
                def yy_of(n):
                    m = re.search(r"(\d{2})$", n)
                    return int(m.group(1)) if m else -1

                candidates.sort(key=yy_of, reverse=True)
                return candidates[0]

        raise QgsProcessingException(
            self.tr(f"Kolom untuk tema ini tidak ditemukan (template: {templ}).")
        )

    def _palette_for(self, theme_index, layer):
        if theme_index in (self.THEME_IKP_AIR,):
            return self._palette_ikp_air(layer)
        if theme_index in (self.THEME_IKP_KEHATI,):
            return self._palette_ikp_kehati(layer)
        if theme_index in (self.THEME_IKP_LAHAN,):
            return self._palette_ikp_lahan(layer)
        if theme_index in (self.THEME_IKP_UDARA,):
            return self._palette_ikp_udara(layer)
        # default untuk seluruh JLH
        return self._palette_jlh(layer)

    # -------------------- main -----------------------
    def processAlgorithm(self, parameters, context, feedback):
        layer = self.parameterAsLayer(parameters, self.P_LAYER, context)
        if layer is None:
            raise QgsProcessingException(self.tr("Layer tidak valid."))

        theme_index = self.parameterAsEnum(parameters, self.P_THEME, context)
        year_opt = (
            self.parameterAsInt(parameters, self.P_YEAR, context)
            if parameters.get(self.P_YEAR) is not None
            else None
        )

        field_name = (
            self.parameterAsString(parameters, self.P_FIELD, context) or ""
        ).strip()
        if not field_name:
            field_name = self._autodetect_field(layer, theme_index, year_opt)

        categories = self._palette_for(theme_index, layer)

        renderer = QgsCategorizedSymbolRenderer(field_name, categories)
        layer.setRenderer(renderer)
        layer.setName(f"{layer.name()}")
        layer.triggerRepaint()
        return {}
