# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OtomatisasiD3TLH
                                 A QGIS plugin
 Plugin yang membantu pengolahan D3TLH secara otomatis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-15
        copyright            : (C) 2025 by Yayasan Lokahita
        email                : fadillahazhardk@yayasanlokahita.org
 ***************************************************************************/

 /***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yayasan Lokahita'
__date__ = '2025-08-15'
__copyright__ = '(C) 2025 by Yayasan Lokahita'

# This will get replaced with a git SHA1 when you do a git archive
__revision__ = '$Format:%H$'

import math
from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (
    QgsProcessing, QgsProcessingException,
    QgsProcessingAlgorithm,
    QgsProcessingParameterExtent,
    QgsProcessingParameterEnum,
    QgsProcessingParameterCrs,
    QgsProcessingParameterFeatureSink,
    QgsCoordinateReferenceSystem,
    QgsFeature, QgsFields, QgsField, QgsGeometry, QgsPointXY,
    QgsWkbTypes, QgsFeatureSink
)

# Origin sistem grid Indonesia
ORI_LAT_MIN = -15.0  # LS (naik ke utara)
ORI_LON_MIN = 90.0   # BT (naik ke timur)


class UtilsGridSGSRIAlgorithm(QgsProcessingAlgorithm):
    P_EXTENT = "P_EXTENT"
    P_GRID_SIZE = "P_GRID_SIZE"
    P_CRS = "P_CRS"
    P_OUT = "P_OUT"

    # (label, d_lat, d_lon)
    GRID_CHOICES = [
        ("1° × 1°30′  (≈111.0 × 166.5 km)", 1.0, 1.5),          # KB
        ("30′ × 30′   (≈55.50 × 55.50 km)", 0.5, 0.5),           # KB C
        ("15′ × 15′   (≈27.75 × 27.75 km)", 0.25, 0.25),         # KB C D
        ("7′30″ × 7′30″ (≈13.875 × 13.875 km)", 0.125, 0.125),   # KB C D E
        ("2′30″ × 2′30″ (≈4.625 × 4.625 km)", 1.0/24.0, 1.0/24.0),   # KB C D E F
        ("30″ × 30″   (≈0.900 × 0.900 km)", 1.0/120.0, 1.0/120.0),   # KB C D E F G
        ("5″ × 5″     (≈0.150 × 0.150 km)", 1.0/720.0, 1.0/720.0),   # KB C D E F G H
    ]

    def tr(self, s): return QCoreApplication.translate("Processing", s)
    def name(self): return "generategrid"
    def displayName(self): return self.tr("Pembuatan Grid Skala Ragam Indonesia (SGSRI)")
    def groupId(self): return "A. Utilities"
    def group(self): return self.tr(self.groupId())
    def createInstance(self): return UtilsGridSGSRIAlgorithm()

    def shortHelpString(self):
        return self.tr("""\
            Sistem Grid Skala Ragam Indonesia (Indonesian Multi-scale Grid System/IMGS) dirancang sebagai struktur grid berbasis sel persegi yang menyerupai format data raster. Setiap sel memiliki koordinat unik dan atribut yang memungkinkan representasi fenomena geografis secara kontinu dan terstruktur. IMGS mengadopsi Sistem Referensi Geospasial Indonesia (SRGI) 2013 sebagai acuan geodetik nasional, dengan titik asal pada 90° BT dan 15° LS agar selaras dengan sistem penomoran lembar peta Rupa Bumi Indonesia (RBI). 

            Pilihan ukuran GRID:
            • 1° × 1°30′ (≈111.0 × 166.5 km) 
            • 30′ × 30′ (≈55.50 × 55.50 km)  
            • 15′ × 15′ (≈27.75 × 27.75 km)  
            • 7′30″ × 7′30″ (≈13.875 × 13.875 km)  
            • 2′30″ × 2′30″ (≈4.625 × 4.625 km)  
            • 30″ × 30″ (≈0.900 × 0.900 km)  
            • 5″ × 5″ (≈0.150 × 0.150 km)"""
        )

    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterExtent(
            self.P_EXTENT, self.tr("Extent pembuatan grid (EPSG:4326)")
        ))
        self.addParameter(QgsProcessingParameterEnum(
            self.P_GRID_SIZE, self.tr("Ukuran grid"),
            options=[c[0] for c in self.GRID_CHOICES], defaultValue=5
        ))
        self.addParameter(QgsProcessingParameterCrs(
            self.P_CRS, self.tr("CRS keluaran"),
            defaultValue=QgsCoordinateReferenceSystem("EPSG:4326"), optional=True
        ))
        self.addParameter(QgsProcessingParameterFeatureSink(
            self.P_OUT, self.tr("SGSRI"),
            type=QgsProcessing.TypeVectorPolygon
        ))

    # ---------- helper penamaan KB–H ----------
    @staticmethod
    def _pad2(v: int) -> str:
        return f"{v:02d}"

    @staticmethod
    def _idx(offset_deg: float, step_deg: float) -> int:
        # indeks 1-based, stabil di batas grid
        eps = 1e-12
        return int(math.floor((offset_deg - eps) / step_deg)) + 1

    def _make_hier_id(self, x_cent: float, y_cent: float, d_lat: float, d_lon: float) -> str:
        """Hitung ID hierarkis berdasarkan pusat sel dan resolusi terpilih."""
        # Induk 1.5° (lon) × 1° (lat)
        dx = x_cent - ORI_LON_MIN
        dy = y_cent - ORI_LAT_MIN

        K = self._idx(dx, 1.5)         # kolom induk
        B = self._idx(dy, 1.0)         # baris induk

        # Sisa dalam induk (derajat → menit)
        rem_lon = dx - (K - 1) * 1.5
        rem_lat = dy - (B - 1) * 1.0
        m = rem_lon * 60.0
        n = rem_lat * 60.0

        # 30′: 3 (lon) × 2 (lat)
        M = self._idx(m, 30.0)         # 1..3
        N = self._idx(n, 30.0)         # 1..2
        C = M + (N - 1) * 3

        # 15′: 2×2 dalam 30′
        o = m - (M - 1) * 30.0
        p = n - (N - 1) * 30.0
        O = self._idx(o, 15.0)
        P = self._idx(p, 15.0)
        D = O + (P - 1) * 2

        # 7′30″: 2×2 dalam 15′
        q = o - (O - 1) * 15.0
        r = p - (P - 1) * 15.0
        Q = self._idx(q, 7.5)
        R = self._idx(r, 7.5)
        E = Q + (R - 1) * 2

        # 2′30″: 3×3 dalam 7′30″
        s = q - (Q - 1) * 7.5
        t = r - (R - 1) * 7.5
        S = self._idx(s, 2.5)
        T = self._idx(t, 2.5)
        F = S + (T - 1) * 3

        # 30″: 5×5 dalam 2′30″
        i30 = s - (S - 1) * 2.5
        n30 = t - (T - 1) * 2.5
        I30 = self._idx(i30, 0.5)
        N30 = self._idx(n30, 0.5)
        G = I30 + (N30 - 1) * 5

        # 5″: 6×6 dalam 30″
        u = (i30 - (I30 - 1) * 0.5) * 60.0
        v = (n30 - (N30 - 1) * 0.5) * 60.0
        U = self._idx(u, 5.0)
        V = self._idx(v, 5.0)
        H = U + (V - 1) * 6

        # rakit ID sesuai resolusi yang dipilih
        # (dibedakan via d_lat/d_lon)
        def isclose(a, b): return math.isclose(a, b, rel_tol=1e-10, abs_tol=1e-12)

        kb = self._pad2(K) + self._pad2(B)
        if isclose(d_lat, 1.0) and isclose(d_lon, 1.5):      # 1°×1°30′
            return kb
        if isclose(d_lat, 0.5) and isclose(d_lon, 0.5):      # 30′
            return kb + str(C)
        if isclose(d_lat, 0.25) and isclose(d_lon, 0.25):    # 15′
            return kb + str(C) + str(D)
        if isclose(d_lat, 0.125) and isclose(d_lon, 0.125):  # 7′30″
            return kb + str(C) + str(D) + str(E)
        if isclose(d_lat, 1/24) and isclose(d_lon, 1/24):    # 2′30″
            return kb + str(C) + str(D) + str(E) + str(F)
        if isclose(d_lat, 1/120) and isclose(d_lon, 1/120):  # 30″
            return kb + str(C) + str(D) + str(E) + str(F) + f"{G:02d}"
        if isclose(d_lat, 1/720) and isclose(d_lon, 1/720):  # 5″
            return kb + str(C) + str(D) + str(E) + str(F) + f"{G:02d}" + f"{H:02d}"
        # fallback
        return kb

    # ------------------------------------------

    def processAlgorithm(self, parameters, context, feedback):
        extent = self.parameterAsExtent(parameters, self.P_EXTENT, context)
        size_idx = self.parameterAsEnum(parameters, self.P_GRID_SIZE, context)
        crs = self.parameterAsCrs(parameters, self.P_CRS, context)
        if not crs.isValid():
            crs = QgsCoordinateReferenceSystem("EPSG:4326")

        label, d_lat, d_lon = self.GRID_CHOICES[size_idx]

        # snap extent ke grid origin
        def snap_down(v, origin, step):
            return origin + math.floor((v - origin) / step) * step

        xmin = snap_down(extent.xMinimum(), ORI_LON_MIN, d_lon)
        ymin = snap_down(extent.yMinimum(), ORI_LAT_MIN, d_lat)
        xmax = extent.xMaximum()
        ymax = extent.yMaximum()

        fields = QgsFields()
        fields.append(QgsField("ID", QVariant.String))     # nama grid
        fields.append(QgsField("Label", QVariant.String))

        sink, dest_id = self.parameterAsSink(
            parameters, self.P_OUT, context, fields, QgsWkbTypes.Polygon, crs
        )
        if sink is None:
            raise QgsProcessingException(self.tr("Tidak dapat membuat output sink."))

        # progress
        total_cols = int((xmax - xmin) / d_lon) + 2
        total_rows = int((ymax - ymin) / d_lat) + 2
        n_total = total_cols * total_rows
        n = 0

        y = ymin
        while y < ymax + 1e-12:
            x = xmin
            while x < xmax + 1e-12:
                col = int((x - ORI_LON_MIN) / d_lon)   # info tambahan
                row = int((y - ORI_LAT_MIN) / d_lat)

                # geometri
                poly = QgsGeometry.fromPolygonXY([[
                    QgsPointXY(x, y),
                    QgsPointXY(x + d_lon, y),
                    QgsPointXY(x + d_lon, y + d_lat),
                    QgsPointXY(x, y + d_lat),
                    QgsPointXY(x, y),
                ]])

                # pusat sel (untuk ID hierarkis)
                cx = x + d_lon/2.0
                cy = y + d_lat/2.0
                grid_id = self._make_hier_id(cx, cy, d_lat, d_lon)

                f = QgsFeature(fields)
                f.setGeometry(poly)
                f["ID"] = grid_id
                f["Label"] = label
                sink.addFeature(f, QgsFeatureSink.FastInsert)

                n += 1
                if n_total and n % 100 == 0:
                    feedback.setProgress(100.0 * n / n_total)
                x += d_lon
            y += d_lat

        return {self.P_OUT: dest_id}
