# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OtomatisasiD3TLH
                                 A QGIS plugin
 Plugin yang membantu pengolahan D3TLH secara otomatis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-15
        copyright            : (C) 2025 by Yayasan Lokahita
        email                : fadillahazhardk@yayasanlokahita.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yayasan Lokahita'
__date__ = '2025-08-15'
__copyright__ = '(C) 2025 by Yayasan Lokahita'


# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import csv
from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (
    QgsProcessing, QgsFeature, QgsFeatureSink, QgsField, QgsFields,
    QgsProcessingParameterEnum, QgsProcessingParameterField,
    QgsProcessingParameterFeatureSource, QgsProcessingParameterFeatureSink,
    QgsProcessingParameterBoolean,
    QgsProcessingException, QgsProcessingAlgorithm
)

class KlasifikasiPLatauKawasanHutan(QgsProcessingAlgorithm):
    """
    Pilih jenis klasifikasi (PL/Kawasan Hutan), pilih kolom ID dari input,
    join ke lookup table (dibundel di folder algoritma), dan hasilkan
    layer baru dengan kolom LC/kwshutan.
    """

    # ----- keys -----
    INPUT = "INPUT"
    CLASS_TYPE = "CLASS_TYPE"  # enum: 0=PL, 1=Kawasan Hutan
    INPUT_ID_FIELD = "INPUT_ID_FIELD"
    FORCE_ID_TEXT = "FORCE_ID_TEXT"
    OUTPUT = "OUTPUT"

    # ----- constants -----
    CLASS_OPTIONS = ["Penutup Lahan (LC)", "Kawasan Hutan (kwshutan)"]
    OUT_FIELD_LC = "LC"
    OUT_FIELD_KWS = "kwshutan"

    # Nama file lookup yang dibundel
    LOOKUP_PL_FILES = ["lookup_pl.csv", os.path.join("data", "lookup_pl.csv")]
    LOOKUP_KWS_FILES = ["lookup_kws.csv", os.path.join("data", "lookup_kws.csv")]

    # ----- boilerplate -----
    def tr(self, s): return QCoreApplication.translate("Processing", s)
    def createInstance(self): return KlasifikasiPLatauKawasanHutan()
    def name(self): return "klasifikasi_pl_atau_kawasan_hutan"
    def displayName(self): return self.tr("Klasifikasi Penutup Lahan dan Kawasan Hutan KLHK RI")
    def group(self): return self.tr(self.groupId())
    def groupId(self): return "00. Utilities"

    def shortHelpString(self) -> str:
        return self.tr("""\
            🇮🇩 ID Deskripsi:
            Klasifikasikan layer vektor menjadi Penutup Lahan (LC) atau Kawasan Hutan (kwshutan) berdasarkan kode klasifikasi. Algoritma ini digunakan untuk data penutup lahan dan kawasan klasfikasi oleh KLHK RI.
            Alur:
            1) Pilih jenis klasifikasi (PL/Kawasan Hutan)
            2) Pilih layer input dan ID field dari layer tersebut
            3) Memuat atribut klasifikasi:
                 • PL: memuat kolom LC berdasarkan ID field
                 • Kawasan Hutan: memuat kolom kwshutan berdasarkan ID field
            4) Output menambahkan kolom LC atau kwshutan.
           
            ──────────────
            
            🌍 EN Description:
            Classify features as Land Cover (LC) or Forest Area (kwshutan) based on KLHK RI classification standard.
        """)

    # ----- parameters -----
    def initAlgorithm(self, config=None):
        # input layer
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT, self.tr("Input layer"),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )
        # classification type
        self.addParameter(
            QgsProcessingParameterEnum(
                self.CLASS_TYPE, self.tr("Classification type or Jenis klasifikasi"),
                options=self.CLASS_OPTIONS, defaultValue=0
            )
        )
        # id field from input
        self.addParameter(
            QgsProcessingParameterField(
                self.INPUT_ID_FIELD, self.tr("Select the ID field in the input layer (e.g., PL2024_ID atau fungsikws)"),
                parentLayerParameterName=self.INPUT,
                type=QgsProcessingParameterField.Any
            )
        )
        # force id as text
        self.addParameter(
            QgsProcessingParameterBoolean(
                self.FORCE_ID_TEXT, self.tr("Treat ID as text (preserve leading zeros)"),
                defaultValue=True
            )
        )
        # sink
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT, self.tr("Output Layer")
            )
        )

    # ----- utilities -----
    def _resolve_lookup_path(self, filenames):
        base_dir = os.path.dirname(os.path.abspath(__file__))
        for rel in filenames:
            p = os.path.join(base_dir, rel)
            if os.path.isfile(p):
                return p
        return None

    def _read_csv_lookup(self, csv_path, key_col, val_col):
        # Baca CSV jadi dict, cek duplikat kunci
        mapping = {}
        dup_keys = set()
        with open(csv_path, newline='', encoding="utf-8-sig") as f:
            reader = csv.DictReader(f)
            cols = [c.strip() for c in (reader.fieldnames or [])]
            if key_col not in cols or val_col not in cols:
                raise QgsProcessingException(
                    self.tr(f"File '{os.path.basename(csv_path)}' harus memiliki kolom '{key_col}' dan '{val_col}'.")
                )
            for row in reader:
                k_raw = row.get(key_col)
                k = "" if k_raw is None else str(k_raw).strip()
                if k in mapping:
                    dup_keys.add(k)
                mapping[k] = row.get(val_col)
        if dup_keys:
            raise QgsProcessingException(
                self.tr(f"Ditemukan {len(dup_keys)} kunci duplikat pada lookup '{os.path.basename(csv_path)}', contoh: {list(dup_keys)[:5]}")
            )
        return mapping

    # ----- main -----
    def processAlgorithm(self, parameters, context, feedback):
        src = self.parameterAsSource(parameters, self.INPUT, context)
        if src is None:
            raise QgsProcessingException(self.tr("Layer input tidak valid."))

        class_type = self.parameterAsInt(parameters, self.CLASS_TYPE, context)
        id_field = self.parameterAsString(parameters, self.INPUT_ID_FIELD, context)
        force_text = self.parameterAsBool(parameters, self.FORCE_ID_TEXT, context)

        # Tentukan file & skema lookup
        if class_type == 0:
            out_field = self.OUT_FIELD_LC
            key_col, val_col = "CODE", "LC"
            lookup_path = self._resolve_lookup_path(self.LOOKUP_PL_FILES)
            missing_msg = "File lookup PL 'lookup_pl.csv' tidak ditemukan di folder algoritma."
        else:
            out_field = self.OUT_FIELD_KWS
            key_col, val_col = "fungsikws", "kwshutan"
            lookup_path = self._resolve_lookup_path(self.LOOKUP_KWS_FILES)
            missing_msg = "File lookup Kawasan Hutan 'lookup_kws.csv' tidak ditemukan di folder algoritma."

        if not lookup_path:
            raise QgsProcessingException(self.tr(missing_msg))

        lut = self._read_csv_lookup(lookup_path, key_col, val_col)

        # schema output
        in_fields: QgsFields = src.fields()
        out_fields = QgsFields(in_fields)
        if out_fields.indexFromName(out_field) == -1:
            f = QgsField(out_field, QVariant.String)
            try:
                f.setLength(254)
            except Exception:
                pass
            out_fields.append(f)

        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context,
            out_fields, src.wkbType(), src.sourceCrs()
        )

        # iterator fitur: QGIS otomatis hormati "Selected features only" bawaan UI
        feats_iter = src.getFeatures()
        total = max(1, src.featureCount())

        # validasi ID field
        if id_field not in in_fields.names():
            raise QgsProcessingException(self.tr(f"Kolom ID '{id_field}' tidak ditemukan di layer input."))

        out_idx = out_fields.indexFromName(out_field)

        # proses
        n_all = 0
        n_match = 0
        n_null = 0
        null_samples = []

        for i, feat in enumerate(feats_iter):
            if feedback.isCanceled():
                break

            n_all += 1

            attrs = feat.attributes()
            if len(attrs) < out_fields.count():
                attrs += [None] * (out_fields.count() - len(attrs))

            key_val = feat[id_field]
            key_norm = "" if key_val is None else str(key_val)
            if force_text:
                key_norm = key_norm  # preserve zeros; still trim spaces below
            key_norm = key_norm.strip()

            label = lut.get(key_norm, None)
            if label is None:
                n_null += 1
                if len(null_samples) < 5:
                    null_samples.append(key_norm)
            else:
                n_match += 1

            attrs[out_idx] = label

            new_f = QgsFeature(out_fields)
            new_f.setGeometry(feat.geometry())
            new_f.setAttributes(attrs)
            sink.addFeature(new_f, QgsFeatureSink.FastInsert)

            feedback.setProgress(int((i + 1) * (100.0 / total)))

        # ringkasan
        feedback.pushInfo(self.tr("=== Klasifikasi selesai ==="))
        feedback.pushInfo(self.tr(f"Fitur diproses : {n_all}"))
        feedback.pushInfo(self.tr(f"Match          : {n_match}"))
        feedback.pushInfo(self.tr(f"Tidak match    : {n_null}"))
        if n_null:
            feedback.pushInfo(self.tr(f"Contoh ID tidak match (maks 5): {null_samples}"))
            feedback.pushInfo(self.tr("Periksa kembali nilai ID input dan kunci pada lookup CSV."))

        return {self.OUTPUT: dest_id}
